import test from 'node:test';
import assert from 'node:assert/strict';
import {networkState,transactionState,parseKas,miningState,spendState,vaultState} from '../src/models.mjs';
import {NETWORK,requireNetwork,requireBudget,paymentAmount,receiptState} from '../server/testnet-policy.mjs';
import {normalizeTransaction,lookupTransaction} from '../server/transaction.mjs';

test('timing and knowledge over the full slider space',()=>{for(let delay=0;delay<=800;delay++)for(const time of [0,99,100,399,400,delay+100,delay+400,1200]){const s=networkState(delay,time);assert.equal(s.parallel,delay>300);assert.equal(s.parent,delay>300?'A':'B');for(const value of [s.progressB,s.progressC])assert.ok(value>=0&&value<=1);assert.equal(s.secondKnows.includes('B'),s.time>=100+delay);}});
test('transaction conservation is exact, including the invalid endpoint',()=>{for(let tenth=1;tenth<=125;tenth++){const s=transactionState((tenth/10).toFixed(1));if(s.valid)assert.equal(s.paid+s.change+s.fee,s.input);else assert.equal(s.change,null);}assert.equal(transactionState('12.5').valid,false);assert.equal(parseKas('0.00000001'),1n);for(const value of ['NaN','Infinity','-1','1e8','0.000000001','0x10'])assert.equal(parseKas(value),null);});
test('shared input is spent once; rule failures release nothing',()=>{for(const name of ['alice','bob']){const s=spendState(name);assert.equal(s.alice+s.bob,s.input);}for(const action of ['early','large','wrong'])assert.equal(vaultState(action).balance,10000);assert.equal(vaultState('valid').balance,8000);});
test('seeded mining is reproducible and nested by share',()=>{assert.deepEqual(miningState(),miningState());for(let seed=0;seed<100;seed++){const a=miningState(1,seed),b=miningState(10,seed);assert.equal(a.expected,6);assert.equal(b.expected,60);a.blocks.forEach((v,i)=>{if(v.yours)assert.equal(b.blocks[i].yours,true);});}});
test('testnet policy rejects all other networks, bad amounts and excess budgets',()=>{requireNetwork({networkId:NETWORK,isSynced:true,hasUtxoIndex:true});for(const networkId of ['mainnet','testnet','testnet-11','testnet-12',undefined])assert.throws(()=>requireNetwork({networkId,isSynced:true,hasUtxoIndex:true}));assert.throws(()=>requireNetwork({networkId:NETWORK,isSynced:false,hasUtxoIndex:true}));for(const amount of ['0','-1','2','1e-1',1,'0.009'])assert.throws(()=>paymentAmount(amount));assert.equal(paymentAmount('0.1'),10000000n);requireBudget({amount:100000000n,fee:1000000n});assert.throws(()=>requireBudget({amount:100000000n,fee:1000001n}));assert.throws(()=>requireBudget({amount:100000000n,fee:1n,spent:950000000n}));});
test('receipts separate observed amounts, acceptance and expiry',()=>{assert.equal(receiptState({requested:10n,received:0n,expired:true}),'Expired without an observed payment');assert.match(receiptState({requested:10n,received:1n,accepted:true}),/Partial/);assert.match(receiptState({requested:10n,received:11n,accepted:true}),/Overpayment/);assert.match(receiptState({requested:10n,received:10n,accepted:false}),/not yet verified/);});
test('missing and unsafe provider amounts are unavailable, never zero',()=>{const id='a'.repeat(64);const record=normalizeTransaction({transaction_id:id});assert.equal(record.inputSompi,null);assert.equal(record.outputSompi,null);assert.equal(record.feeSompi,null);const large=normalizeTransaction({transaction_id:id,inputs:[{previous_outpoint_amount:Number.MAX_SAFE_INTEGER+1}],outputs:[{amount:1}]});assert.equal(large.feeSompi,null);});
test('provider lookup bounds payloads and validates transaction identity',async()=>{const id='b'.repeat(64);assert.equal((await lookupTransaction('x',()=>{throw Error('must not fetch');})).status,400);assert.equal((await lookupTransaction(id,async()=>new Response(JSON.stringify({transaction_id:'a'.repeat(64)})))).status,502);assert.equal((await lookupTransaction(id,async()=>new Response('x'.repeat(2000001)))).status,502);assert.equal((await lookupTransaction(id,async()=>new Response('',{status:404}))).status,404);});
