import test from 'node:test';import assert from 'node:assert/strict';
import {createMarket,proposeTrade,acceptTrade,prepareTrade,commitTrade,counterTrade,stepMarket,configureAssistant,registerMarketPlayer,getMarketView,RESOURCES} from '../src/v5-market.mjs';
const total=m=>Object.fromEntries(RESOURCES.map(k=>[k,Object.values(m.actors).reduce((s,a)=>s+a.inventory[k],0)]));
const offer=m=>proposeTrade(m,{from:'player',to:'nell',give:{crops:2},want:{bread:1}});
test('player barter conserves resources and settles once',()=>{const m=createMarket({playerInventory:{crops:8}}),before=total(m),t=offer(m);assert.throws(()=>acceptTrade(m,t.id),/approval/);assert.equal(acceptTrade(m,t.id,{playerApproved:true}).status,'settled');assert.deepEqual(total(m),before);const inv=structuredClone(m.actors);acceptTrade(m,t.id,{playerApproved:true});assert.deepEqual(m.actors,inv);});
test('prepared trade reserves resources and requires host receipt before effects',()=>{const m=createMarket({playerInventory:{crops:2}}),t=proposeTrade(m,{from:'player',to:'nell',give:{crops:2},want:{bread:1},requiresReceipt:true});prepareTrade(m,t.id,{playerApproved:true});assert.equal(m.actors.player.inventory.crops,2);assert.equal(acceptTrade(m,offer(m).id,{playerApproved:true}).status,'unfunded');assert.throws(()=>commitTrade(m,t.id),/receipt/);commitTrade(m,t.id,{verifiedReceipt:'host-verified-tx'});assert.equal(m.actors.player.inventory.crops,0);});
test('offers expire and counteroffers supersede original',()=>{const m=createMarket({playerInventory:{crops:8}}),t=offer(m);const c=counterTrade(m,t.id);assert.equal(c.from,'nell');assert.throws(()=>acceptTrade(m,t.id,{playerApproved:true}),/no longer/);const exp=offer(m);stepMarket(m,70);assert.throws(()=>acceptTrade(m,exp.id,{playerApproved:true}),/no longer|expired/);});
test('scarcity and offer quantities change negotiation',()=>{const m=createMarket({playerInventory:{crops:20}});assert.equal(offer(m).decision,'accept');assert.equal(proposeTrade(m,{from:'player',to:'nell',give:{crops:1},want:{bread:10}}).decision,'counter');m.actors.nell.inventory.bread=0;assert.equal(offer(m).decision,'unfunded');});
test('agents produce and trade deterministically with accounted resource changes',()=>{const m=createMarket(),before=total(m),other=createMarket();stepMarket(m,100);stepMarket(other,100);assert.deepEqual(m,other);assert.ok(m.events.some(e=>e.type==='barter'));assert.ok(m.events.some(e=>e.type==='production'));const after=total(m);for(const k of RESOURCES)assert.equal(after[k],before[k]+m.production.created[k]-m.production.consumed[k]-m.consumption[k]);for(const a of Object.values(m.actors))for(const n of Object.values(a.inventory))assert.ok(n>=0);});
test('assistant disabled by default and total resource caps bound autonomous authority',()=>{const m=createMarket({playerInventory:{crops:30}});stepMarket(m,10);assert.equal(m.actors.player.inventory.crops,30);configureAssistant(m,{enabled:true,maxTradesPerTick:2,maxGive:{crops:2}});stepMarket(m,200);assert.ok(m.assistant.spent.crops<=2);assert.ok(m.actors.player.inventory.crops>=28);assert.throws(()=>stepMarket(m,0),/monotonic/);});
test('automatic assistant trades are marked delegated while manual approval stays unmarked',()=>{
 const manual=createMarket({playerInventory:{crops:8}}),manualOffer=offer(manual);
 assert.equal(acceptTrade(manual,manualOffer.id,{playerApproved:true}).status,'settled');
 assert.equal(manual.trades[manualOffer.id].delegated,undefined);
 for(const requiresReceipt of [false,true]){
  const automatic=createMarket({playerInventory:{crops:30}});automatic.playerTradesRequireReceipt=requiresReceipt;
  configureAssistant(automatic,{enabled:true,maxTradesPerTick:2,maxGive:{crops:2}});stepMarket(automatic,10);
  const trade=Object.values(automatic.trades).find(t=>t.from==='player'&&t.to==='nell'&&t.give.crops===1&&t.want.bread===1);
  assert.ok(trade,'assistant should produce the deterministic crop-to-bread trade');
  assert.equal(trade.status,requiresReceipt?'prepared':'settled');
  assert.equal(trade.delegated,true);
 }
});
test('same verified receipt cannot settle a second trade',()=>{const m=createMarket({playerInventory:{crops:6}});const make=()=>proposeTrade(m,{from:'player',to:'nell',give:{crops:2},want:{bread:1},requiresReceipt:true});const a=make();prepareTrade(m,a.id,{playerApproved:true});commitTrade(m,a.id,{verifiedReceipt:'receipt-1'});const b=make();prepareTrade(m,b.id,{playerApproved:true});assert.throws(()=>commitTrade(m,b.id,{verifiedReceipt:'receipt-1'}),/already used/);assert.equal(m.actors.player.inventory.crops,4);});
test('production cannot consume reserved trade inputs',()=>{const m=createMarket({playerInventory:{bread:10}});m.actors.rowan.inventory.bread=1;const t=proposeTrade(m,{from:'rowan',to:'player',give:{bread:1},want:{bread:1},requiresReceipt:true});prepareTrade(m,t.id,{playerApproved:true});const wood=m.actors.rowan.inventory.wood;stepMarket(m,10);assert.ok(m.actors.rowan.inventory.wood<=wood);assert.equal(m.trades[t.id].status,'prepared');});
test('shared players retain independent inventories and assistant authority',()=>{const m=createMarket({playerInventory:{crops:0}});registerMarketPlayer(m,{id:'alice',inventory:{crops:8,bread:0}});registerMarketPlayer(m,{id:'bob',inventory:{wood:4}});configureAssistant(m,{playerId:'alice',enabled:true,maxGive:{crops:1}});assert.equal(getMarketView(m,{playerId:'alice'}).assistant.enabled,true);assert.equal(getMarketView(m,{playerId:'bob'}).assistant.enabled,false);const t=proposeTrade(m,{from:'alice',to:'bob',give:{crops:2},want:{wood:1}});assert.equal(acceptTrade(m,t.id,{playerApproved:true}).status,'settled');assert.equal(m.actors.bob.inventory.crops,2);assert.equal(m.actors.alice.inventory.wood,1);});
test('long running market remains productive with finite stock and bounded routine history',()=>{const m=createMarket();stepMarket(m,1000);const before=m.production.created.bread;stepMarket(m,2000);assert.ok(m.production.created.bread>before);assert.ok(m.events.length<=200);assert.ok(Object.keys(m.trades).length<=300);for(const a of Object.values(m.actors))for(const n of Object.values(a.inventory))assert.ok(n>=0&&n<=60);stepMarket(m,100000);assert.equal(m.time,100000);const tick=m.tick;stepMarket(m,100000);assert.equal(m.tick,tick);});
test('assistant-off player sees actionable quotes without inventory spending',()=>{const m=createMarket({playerInventory:{crops:20}});stepMarket(m,10);assert.ok(Object.values(m.trades).some(t=>t.from==='player'||t.to==='player'));assert.equal(m.actors.player.inventory.crops,20);});
test('persistent service requires chain settlement, authenticates parties and replays action once',async()=>{const {V5MarketService}=await import('../faucet/v5-market-service.mjs');const data=new Map();const storage={get:async k=>structuredClone(data.get(k)),put:async(k,v)=>{if(typeof k==='object')for(const[a,b]of Object.entries(k))data.set(a,structuredClone(b));else data.set(k,structuredClone(v));}};const service=new V5MarketService({storage,now:()=>0});await service.ensurePlayer({id:'alice'});await service.ensurePlayer({id:'bob'});const action={id:'offer-1',type:'market_propose',to:'nell',give:{crops:2},want:{bread:1}};const first=await service.action('alice',action);assert.deepEqual(await service.action('alice',action),first);const tradeId=first.result.id;await assert.rejects(()=>service.action('bob',{id:'steal',type:'market_accept',tradeId}),/belong/);const ready=await service.action('alice',{id:'accept-1',type:'market_accept',tradeId});assert.equal(ready.result.status,'prepared');assert.equal(ready.market.actors.alice.inventory.crops,6);await service.settle({tradeId,verifiedReceipt:'verified-receipt'});assert.equal((await service.view('alice')).actors.alice.inventory.crops,4);assert.equal(await service.deposit({playerId:'alice',sourceId:'crop-harvest-1',inventory:{crops:2}}),true);assert.equal(await service.deposit({playerId:'alice',sourceId:'crop-harvest-1',inventory:{crops:2}}),false);});
test('service rejects conflicting action IDs and unauthorized custom counters',async()=>{const {V5MarketService}=await import('../faucet/v5-market-service.mjs');const data=new Map();const storage={get:async k=>structuredClone(data.get(k)),put:async(k,v)=>{for(const[a,b]of typeof k==='object'?Object.entries(k):[[k,v]])data.set(a,structuredClone(b));}};const service=new V5MarketService({storage,now:()=>0});await assert.rejects(()=>service.ensurePlayer({id:'__proto__'}),/Invalid/);await service.ensurePlayer({id:'alice'});const action={id:'one',type:'market_propose',to:'nell',give:{crops:2},want:{bread:1}};const {result}=await service.action('alice',action);await assert.rejects(()=>service.action('alice',{...action,want:{bread:2}}),/different content/);await assert.rejects(()=>service.action('alice',{id:'two',type:'market_counter',tradeId:result.id,give:{bread:1}}),/recipient/);const counter=await service.action('alice',{id:'three',type:'market_counter',tradeId:result.id});assert.equal(counter.result.from,'nell');assert.throws(()=>proposeTrade(createMarket(),{from:'__proto__',to:'nell',give:{crops:1},want:{bread:1}}),/Unknown/);});
test('pending host resolver leaves unverified trade reserved and sync protects reservations',async()=>{const {V5MarketService}=await import('../faucet/v5-market-service.mjs');const data=new Map();const storage={get:async k=>structuredClone(data.get(k)),put:async(k,v)=>{for(const[a,b]of typeof k==='object'?Object.entries(k):[[k,v]])data.set(a,structuredClone(b));}};const s=new V5MarketService({storage,now:()=>0});await s.ensurePlayer({id:'alice'});const {result}=await s.action('alice',{id:'p',type:'market_propose',to:'nell',give:{crops:2},want:{bread:1}});await s.action('alice',{id:'a',type:'market_accept',tradeId:result.id});assert.equal((await s.pending()).length,1);assert.deepEqual(await s.resolvePending(async()=>null),[]);await assert.rejects(()=>s.syncPlayerInventory({playerId:'alice',sourceId:'one',inventory:{crops:1}}),/reserved/);assert.equal((await s.resolvePending(async()=> 'verified-chain-receipt')).length,1);assert.equal((await s.pending()).length,0);await s.syncPlayerInventory({playerId:'alice',sourceId:'two',inventory:{crops:5}});assert.equal((await s.view('alice')).actors.alice.inventory.crops,5);});
