import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
import {reviewV5MarketPlan,signV5MarketPayment} from '../src/v5-market-wallet.mjs';
import {v5ArgentInitialState,buildV5ArgentGenesis,buildV5ArgentTrade,buildV5ArgentConfigure,buildV5ArgentRestock,buildV5ArgentFund,signV5ArgentPlan,v5ArgentWirePlan,v5ArgentCertificateDigest} from '../src/v5-argent-protocol.mjs';
const sdk=createRequire(import.meta.url)('../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa'),templates=JSON.parse(await readFile(new URL('../src/v5-argent-templates.json',import.meta.url)));
const keys=['11','12'].map(v=>new sdk.PrivateKey(v.repeat(32))),owners=keys.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()),address=keys[0].toAddress('testnet-10').toString(),treasuryAddress=keys[1].toAddress('testnet-10').toString(),playerId='ab'.repeat(32),world='cd'.repeat(32);let counter=100;
const funding=(index=1)=>new sdk.UtxoEntries([{outpoint:{transactionId:(counter++).toString(16).padStart(2,'0').repeat(32),index:0},amount:10000000000n,scriptPublicKey:sdk.payToAddressScript(keys[index].toAddress('testnet-10')),blockDaaScore:0n,isCoinbase:false}]).items;
async function makeCell(index){const state=v5ArgentInitialState({owner:owners[index],issuer:owners[1],world,resources:{crops:20,wood:20,ore:20,tools:20,bread:20}}),p=buildV5ArgentGenesis(sdk,{templates,state,deposit:1000000000n,fundingUtxos:funding()});await signV5ArgentPlan(p,(tx,i)=>sdk.createInputSignature(tx,i,keys[1]));const out=p.transaction.outputs[0],utxo=new sdk.UtxoEntries([{outpoint:{transactionId:p.transaction.id,index:0},amount:out.value,scriptPublicKey:out.scriptPublicKey,covenant_id:out.covenant.covenantId.toString(),blockDaaScore:0n,isCoinbase:false}]).items[0],certificate=sdk.signScriptHash(await v5ArgentCertificateDigest({world,covenantId:out.covenant.covenantId.toString(),owner:state.owner},webcrypto),keys[1]).slice(2,-2);return{state,utxo,certificate};}
const left=await makeCell(0),right=await makeCell(1),trade={id:'trade-one',from:playerId,to:'mira',give:{crops:3},want:{bread:2}},expectedCell={covenantId:left.utxo.entry.covenantId.toString(),transactionId:left.utxo.outpoint.transactionId,outpoint:left.utxo.outpoint,state:left.state};
async function options({operation='trade',deltas={crops:-3,bread:2},policy,resources,amountSompi='100000000',fundingOwner=operation==='fund'?0:1,consent={trade,action:{type:'market_accept',tradeId:trade.id}},tradeReview=trade}={}){
 const common={templates,fundingUtxos:funding(fundingOwner)},p=operation==='fund'?buildV5ArgentFund(sdk,{...common,cell:left,amountSompi}):operation==='trade'?buildV5ArgentTrade(sdk,{...common,left,right,deltas}):operation==='configure'?buildV5ArgentConfigure(sdk,{...common,cell:left,policy}):buildV5ArgentRestock(sdk,{...common,cell:left,resources});await signV5ArgentPlan(p,(tx,i)=>sdk.createInputSignature(tx,i,keys[1]),{owners:[owners[1]]});
 const marketPlan={version:1,operation,actors:operation==='trade'?[playerId,'mira']:[playerId],tradeId:tradeReview.id,issuer:owners[1],world,wire:v5ArgentWirePlan(p),economicReview:{playerId,playerOwner:owners[0],feePayer:owners[fundingOwner],trade:tradeReview},requiredSignatures:p.signers.flatMap((s,i)=>s.owners.flatMap((owner,j)=>p.signatures[i][j]?[]:[{inputIndex:i,signatureIndex:j,owner}]))};return{templates,payment:{marketPlan},address,treasuryAddress,playerId,consent,expectedCell};
}
test('review accepts and signs only the exact manually reviewed bilateral resource delta',async()=>{const o=await options();assert.equal(reviewV5MarketPlan(sdk,o).operation,'trade');const signed=await signV5MarketPayment(sdk,o,keys[0]);assert.equal(signed.signatures.length,1);assert.equal(signed.signatures[0].inputIndex,0);assert.match(signed.signatures[0].signature,/^[0-9a-f]{128}01$/);});
test('review rejects altered resources, unexpected native debit, and missing explicit trade consent',async()=>{const changed=await options({deltas:{crops:-4,bread:2}});assert.throws(()=>reviewV5MarketPlan(sdk,changed),/quantities/);const debit=await options({deltas:{crops:-3,bread:2,coin:-1000000}});assert.throws(()=>reviewV5MarketPlan(sdk,debit),/test coins/);const noConsent=await options({consent:null});assert.throws(()=>reviewV5MarketPlan(sdk,noConsent),/exact trade/);});
test('review anchors the previously confirmed business lineage, output index, and state',async()=>{for(const mutate of[c=>c.covenantId='ee'.repeat(32),c=>c.transactionId='ee'.repeat(32),c=>c.outpoint={index:1},c=>c.state={...c.state,crops:99}]){const o=await options();o.expectedCell=structuredClone(expectedCell);mutate(o.expectedCell);assert.throws(()=>reviewV5MarketPlan(sdk,o),/last accepted state/);}});
test('review rejects unexpected signature slots and fee payer',async()=>{const o=await options();o.payment.marketPlan.requiredSignatures.push({inputIndex:1,signatureIndex:0,owner:owners[1]});assert.throws(()=>reviewV5MarketPlan(sdk,o),/signature request/);const fee=await options();fee.payment.marketPlan.economicReview.feePayer=owners[0];assert.throws(()=>reviewV5MarketPlan(sdk,fee),/issuer changed/);});
test('review accepts exact cumulative assistant allowances and rejects extra authority',async()=>{const consent={action:{type:'market_assistant',enabled:true,maxGive:{crops:5}}},policy={operator:owners[1],allow_crops:5,min_receive:1},o=await options({operation:'configure',policy,consent});assert.equal(reviewV5MarketPlan(sdk,o).states[0].allow_crops,5);const expanded=await options({operation:'configure',policy:{...policy,allow_wood:1},consent});assert.throws(()=>reviewV5MarketPlan(sdk,expanded),/spending limit/);const coins=await options({operation:'configure',policy:{...policy,allow_coin:1},consent});assert.throws(()=>reviewV5MarketPlan(sdk,coins),/authority/);});
test('review accepts exact native purchase and rejects a price above consent',async()=>{const t={id:'buy-one',from:playerId,to:'mira',give:{},want:{crops:2},nativeAmountSompi:'10000000'},consent={action:{type:'market_buy',to:'mira',resource:'crops',amount:2,maxTotalSompi:'10000000'}},o=await options({deltas:{crops:2,coin:-10000000},tradeReview:t,consent});assert.equal(reviewV5MarketPlan(sdk,o).operation,'trade');o.consent.action.maxTotalSompi='9999999';assert.throws(()=>reviewV5MarketPlan(sdk,o),/price/);});
test('restock must exactly match the previously observed inventory target',async()=>{const o=await options({operation:'restock',resources:{crops:2}});o.expectedInventory={...left.state,crops:22};assert.equal(reviewV5MarketPlan(sdk,o).states[0].crops,22);o.expectedInventory.crops=21;assert.throws(()=>reviewV5MarketPlan(sdk,o),/trading inventory/);});
test('review rejects the same quantities redirected to a different named counterparty',async()=>{const o=await options();o.payment.marketPlan.actors[1]='rowan';assert.throws(()=>reviewV5MarketPlan(sdk,o),/counterparty|participant|business|trade/);});
test('review accepts exact owner-funded business top-up and rejects changed amount or absent consent',async()=>{const consent={action:{type:'market_fund',amountSompi:'100000000'}},o=await options({operation:'fund',consent});const p=reviewV5MarketPlan(sdk,o);assert.equal(p.operation,'fund');assert.equal(p.transaction.outputs[0].value-p.transaction.inputs[0].utxo.amount,100000000n);assert.equal(p.states[0].crops,p.inputStates[0].crops);const signed=await signV5MarketPayment(sdk,o,keys[0]);assert.equal(signed.signatures.length,2);o.consent.action.amountSompi='99999999';assert.throws(()=>reviewV5MarketPlan(sdk,o),/amount|fund|store|coins|deposit|top/i);const noConsent=await options({operation:'fund',consent:null});assert.throws(()=>reviewV5MarketPlan(sdk,noConsent),/fund|store|coins|deposit|top|issuer/i);});
test('a top-up consent cannot be substituted with a wallet-paid restock operation',async()=>{const o=await options({operation:'restock',resources:{crops:1},fundingOwner:0,consent:{action:{type:'market_fund',amountSompi:'100000000'}}});o.expectedInventory={...left.state,crops:21};assert.throws(()=>reviewV5MarketPlan(sdk,o),/operation|fund|transfer|requested/i);});

const materialRecipes={feed_habitat:{requires:{crops:3},recipientId:'habitat-keeper'},build_workshop:{requires:{wood:2,ore:1,tools:1},recipientId:'town-builder'},expand_greenhouse:{requires:{wood:3,tools:2},recipientId:'town-builder'}};
async function materialOptions(purpose='feed_habitat') {const recipe=materialRecipes[purpose],t={id:'use-'+purpose,from:playerId,to:recipe.recipientId,give:{...recipe.requires},want:{},nativeAmountSompi:'0',purpose},o=await options({deltas:Object.fromEntries(Object.entries(recipe.requires).map(([r,n])=>[r,-n])),tradeReview:t,consent:{action:{type:'market_use',purpose}}});o.payment.marketPlan.actors=[playerId,recipe.recipientId];o.payment.marketPlan.economicReview.use={purpose,...structuredClone(recipe)};return o;}
test('all material uses sign only their exact recipe and preserve native balance and unrelated state',async()=>{for(const purpose of Object.keys(materialRecipes)){const o=await materialOptions(purpose),before=structuredClone(o.expectedCell.state),p=reviewV5MarketPlan(sdk,o);assert.equal(p.transaction.outputs[0].value,p.transaction.inputs[0].utxo.amount);for(const key of ['owner','issuer','world','operator','allow_crops','allow_wood','allow_ore','allow_tools','allow_bread','allow_coin','min_receive'])assert.equal(p.states[0][key],p.inputStates[0][key]);assert.equal((await signV5MarketPayment(sdk,o,keys[0])).signatures.length,1);assert.deepEqual(o.expectedCell.state,before,'Signing does not apply an accepted game or covenant successor.');}});
test('material-use review rejects receipt recipe metadata that would fail after node acceptance',async()=>{for(const requires of [{crops:2},{crops:3,wood:1},{crops:'3'}]){const o=await materialOptions();o.payment.marketPlan.economicReview.use.requires=requires;assert.throws(()=>reviewV5MarketPlan(sdk,o),/material|purpose|recipe|quantity/i);}});
test('material-use review requires numeric exact trade quantities and consistent zero-coin purpose metadata',async()=>{for(const mutate of [t=>t.give.crops='3',t=>t.purpose='build_workshop',t=>t.nativeAmountSompi='1']){const o=await materialOptions();mutate(o.payment.marketPlan.economicReview.trade);assert.throws(()=>reviewV5MarketPlan(sdk,o),/material|purpose|recipe|quantity|coin/i);}});
