import {test} from 'node:test';import assert from 'node:assert/strict';
import {createGame,applyGameAction,getGameView,applyMarketUse,quoteMarketUse} from '../src/v5-economy.mjs';import {projectV5Town} from '../src/v5-town-model.mjs';
const playerId='ab'.repeat(32),block='cd'.repeat(32),tx=n=>n.toString(16).padStart(2,'0').repeat(32);
function apply(s,action,n,kind,amountSompi){return applyGameAction(s,action,n,{payment:kind?{playerId,actionId:action.id,transactionId:tx(n),acceptingBlock:block,kind,amountSompi}:undefined});}
test('empty town removes legacy simulated wealth and never invents care or accepted transfers',()=>{const w=projectV5Town();assert.equal(w.simulation.factoryBuilt,false);assert.equal(w.simulation.food,0);assert.equal(w.robots.find(r=>r.id==='Pip').budget,0);assert.equal(w.v5Town.companions.careAvailable,false);assert.equal(w.economicLoop,undefined);assert.deepEqual(w.events,[]);assert.equal(w.v5Town.money.walletSompi,null);});
test('pending payment successor never builds or credits inventory before service acceptance',()=>{const s=createGame({playerId,now:1}),snapshot={state:s,payment:{kind:'purchase',status:'pending',transactionId:tx(1),marketPlan:{wire:{states:[{plots:5,crops:999}]}}}};const w=projectV5Town(snapshot);assert.equal(w.simulation.factoryBuilt,false);assert.equal(w.resources.food,0);assert.equal(w.v5Town.receipts.length,0);assert.equal(w.v5Town.pending.status,'pending');});
test('accepted plot purchase and actual planting/harvest drive growing props without projecting time',()=>{let s=createGame({playerId,now:1});s=apply(s,{id:'plot',type:'buy_plot'},2,'purchase',50000000);s=apply(s,{id:'plant',type:'plant'},3);s=apply(s,{id:'water',type:'water'},4);const ripe=projectV5Town({state:s});assert.equal(ripe.v5Town.production.readyCrops,3);assert.equal(ripe.resources.food,0);s=apply(s,{id:'harvest',type:'harvest'},5);const before=structuredClone(s),w=projectV5Town({state:s,balanceSompi:'123000000'});assert.equal(w.simulation.factoryBuilt,true);assert.equal(w.resources.food,3);assert.equal(w.v5Town.production.readyCrops,0);assert.equal(w.v5Town.money.walletSompi,'123000000');assert.equal(w.v5Town.money.purchasedSompi,'50000000');assert.equal(w.v5Town.money.feesComplete,false);assert.deepEqual(s,before);const v=projectV5Town({...getGameView(s,5),receipts:Object.values(s.receipts)});assert.deepEqual(v.v5Town.inventory.farm,w.v5Town.inventory.farm);assert.deepEqual(v.v5Town.buildings,w.v5Town.buildings);});
test('accepted order updates delivery count and treasury earnings without inventing Sprout delivery/care',()=>{let s=createGame({playerId,now:1});for(const [a,n,k,m] of [[{id:'plot',type:'buy_plot'},2,'purchase',50000000],[{id:'plant',type:'plant'},3],[{id:'water',type:'water'},4],[{id:'harvest',type:'harvest'},5],[{id:'order',type:'accept_order',orderId:'first-harvest'},6],[{id:'deliver',type:'deliver_order',orderId:'first-harvest'},7,'reward',25000000]])s=apply(s,a,n,k,m);const w=projectV5Town({state:s});assert.equal(w.v5Town.delivery.completed,1);assert.equal(w.v5Town.delivery.inTransit,false);assert.equal(w.simulation.habitatSupplied,false);assert.equal(w.v5Town.money.earnedSompi,'25000000');assert.equal(w.v5Town.labels.delivery,'1 order completed');assert.equal(w.resources.food,0);assert.equal(w.v5Town.receipts.length,2);});
test('market inventory and proposed assistant settings are distinct from accepted covenant inventory and mandate',()=>{const s=createGame({playerId,now:1}),cell={transactionId:tx(2),acceptingBlock:block,nativeSompi:'200000000',state:{owner:'owner',operator:'issuer',crops:3,wood:4,allow_crops:2,min_receive:1}},market={playerId,actors:{[playerId]:{inventory:{crops:9,wood:7}}},assistant:{enabled:true},cells:{[playerId]:cell}};const w=projectV5Town({state:s,market});assert.equal(w.v5Town.inventory.market.crops,9);assert.equal(w.v5Town.inventory.business.crops,3);assert.equal(w.v5Town.pip.trading,true);assert.equal(w.v5Town.money.businessSompi,'200000000');delete cell.acceptingBlock;const waiting=projectV5Town({state:s,market});assert.equal(waiting.v5Town.inventory.business,null);assert.equal(waiting.v5Town.money.businessSompi,null);assert.equal(waiting.v5Town.pip.trading,false);});

test('accepted material care and construction update existing 3D props without moving Sprout or implying a wage',()=>{const s=createGame({playerId,now:1}),purpose='feed_habitat',proof={...quoteMarketUse(s,purpose,2),playerId,transactionId:tx(9),acceptingBlock:block};const before=projectV5Town({state:s}),fed=projectV5Town({state:applyMarketUse(s,{id:'care',purpose},2,proof)});assert.equal(before.simulation.habitatSupplied,false);assert.equal(fed.simulation.habitatSupplied,true);assert.equal(fed.simulation.food,3);assert.equal(fed.creatures.find(c=>c.id==='Sprout').energy,12);assert.equal(fed.creatures.find(c=>c.id==='Sprout').x,before.creatures.find(c=>c.id==='Sprout').x);assert.equal(fed.v5Town.money.earnedSompi,'0');assert.equal(fed.v5Town.labels.food,'3 crops supplied');assert.equal(fed.v5Town.labels.props['terrarium:feed'].text,'Care for Sprout again');assert.equal(fed.events[0].detail.includes('undefined'),false);assert(!JSON.stringify(fed.v5Town.labels).includes('all 3'));const build='expand_greenhouse',built=projectV5Town({state:applyMarketUse(s,{id:'expand',purpose:build},2,{...quoteMarketUse(s,build,2),playerId,transactionId:tx(10),acceptingBlock:block})});assert.equal(built.simulation.factoryBuilt,true);assert.equal(built.v5Town.labels.build,'1 growing plot');});

test('one accepted material transaction retains its care purpose when also listed as a market receipt',()=>{const s=createGame({playerId,now:1}),purpose='feed_habitat',next=applyMarketUse(s,{id:'care',purpose},2,{...quoteMarketUse(s,purpose,2),playerId,transactionId:tx(12),acceptingBlock:block}),w=projectV5Town({state:next,marketReceipts:[{transactionId:tx(12),acceptingBlock:block,kind:'market',operation:'trade',feeSompi:'1234'}]});assert.equal(w.v5Town.receipts.length,1);assert.equal(w.v5Town.receipts[0].purpose,'feed_habitat');assert.equal(w.events[0].title,'Sprout’s habitat supplied');assert.equal(w.v5Town.money.knownFeeSompi,'1234');});
