import {readFile,writeFile,mkdir,mkdtemp,rm,copyFile,access,cp} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
import {instantiatePublicContract,buildPublicSpend,signPublicPlan,publicTransactionMass} from '../src/public-contracts.mjs';
import {generateProof} from '../src/v6-proof-protocol.mjs';
import {instantiatePublicReceipt,buildBackedMove,signBackedPlan} from '../src/public-receipt.mjs';
import {v5ArgentInitialState,instantiateV5Argent,buildV5ArgentTrade,v5ArgentCertificateDigest,signV5ArgentPlan,v5ArgentWirePlan} from '../src/v5-argent-protocol.mjs';
export const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const run=promisify(execFile),sdk=createRequire(import.meta.url)('../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa'),hash=b=>createHash('sha256').update(b).digest('hex');
const keys=[11,12,13,14].map(n=>new sdk.PrivateKey(n.toString(16).padStart(2,'0').repeat(32))),owners=keys.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()),world='b5'.repeat(32),exists=p=>access(p).then(()=>true,()=>false),integer=(key,label,def,min,max)=>({key,label,type:'number',default:def,min,max,step:1}),select=(key,label,def,options)=>({key,label,type:'select',default:def,options});
const defs=[
{id:'allowance',title:'Allowance agent',description:'An operator trades inventory within an owner-set allowance and minimum return. The contract rejects spending beyond that allowance.',language:'Argent',fields:[integer('allowance','Maximum inventory units operator may spend',10,1,100),integer('spend','Inventory units spent',4,1,100),integer('receive','Counterparty units received',2,1,100)],file:'contracts/public/argent-market/business.ag'},
{id:'escrow',title:'Escrow',description:'A buyer releases escrow to the seller, an arbiter resolves a dispute, or the buyer refunds after the configured time.',language:'SilverScript',fields:[integer('principal','Escrow principal (sompi)',50000000,20000000,100000000),select('action','Spending path','release',['release','resolve','refund']),integer('refundAfter','Refund time (Unix milliseconds)',1800000240000,1800000000000,1900000000000),integer('currentMedianTime','Synthetic current median time (Unix milliseconds)',1800000300000,1800000000000,1900000000000)],file:'contracts/public/application-escrow.sil'},
{id:'treasury',title:'Shared treasury',description:'Two of three members authorize a payout to a fixed sample beneficiary.',language:'SilverScript',fields:[integer('principal','Treasury principal (sompi)',50000000,20000000,100000000),select('pair','Required member pair','0',['0','1','2']),select('authorization','Authorization fixture','complete',['complete','missing-second'])],file:'contracts/public/shared-treasury.sil'},
{id:'receipt',title:'Reserve-backed receipt',description:'One claim unit is backed by one locked sompi. Redemption pays the holder while a separate sponsor pays the fee.',language:'SilverScript',fields:[integer('backing','Locked backing / claim units (sompi)',60000000,30000000,100000000),integer('redeem','Redeem units (sompi)',30000000,20000000,100000000)],file:'contracts/public/backed-receipt.sil'},
{id:'proof',title:'Proof-gated payout',description:'Generate a Groth16 proof that two bounded witness values multiply to 42 and sum to 13; bind the payout to a sample recipient and nonce. Experimental public setup, not arbitrary useful work.',language:'SilverScript',fields:[integer('principal','Payout principal (sompi)',50000000,30000000,100000000),integer('allocation','Private witness A (1–15)',6,1,15),integer('rate','Private witness B (1–15)',7,1,15),integer('nonce','Task nonce',1,1,1000000),select('proofVariant','Proof fixture','valid',['valid','corrupt'])],file:'contracts/public/proof-payout.sil'}];
for(const d of defs)d.fields.push(integer('feeRate','Fee rate (sompi per mass unit)',100,100,1000));
export function catalog(){return{network:'testnet-10',synthetic:true,examples:defs.map(d=>({...d,defaults:Object.fromEntries(d.fields.map(f=>[f.key,f.default]))}))};}
export function normalize(example,values={}){const d=defs.find(d=>d.id===example);if(!d)throw Error('Unknown example.');if(!values||typeof values!=='object'||Array.isArray(values)||Object.keys(values).some(k=>!d.fields.some(f=>f.key===k)))throw Error('Unexpected configuration fields.');const out={};for(const f of d.fields){const v=values[f.key]??f.default;if(f.type==='number'){if(typeof v!=='number'||!Number.isSafeInteger(v)||v<f.min||v>f.max)throw Error(`${f.label} must be an integer between ${f.min} and ${f.max}.`);}else if(!f.options.includes(v))throw Error('Choose a listed '+f.label.toLowerCase()+'.');out[f.key]=v;}if(example==='allowance'&&out.spend>out.allowance)throw Error('Spend exceeds the operator allowance.');if(example==='receipt'&&(out.redeem>out.backing||out.backing-out.redeem>0&&out.backing-out.redeem<20000000))throw Error('Redemption must not exceed backing; leave zero or at least 20,000,000 backed units to respect storage mass.');return{definition:d,values:out};}
const nativeVmAvailable=async()=>process.env.WORKBENCH_VM_EXECUTABLE?exists(process.env.WORKBENCH_VM_EXECUTABLE):exists(join(ROOT,'.cache/upstream/silverscript/Cargo.toml'));
export async function health(){return{ok:await exists(join(ROOT,'.cache/upstream/silverc'))&&await nativeVmAvailable(),network:'testnet-10',synthetic:true,submitted:false,compiler:{silverScript:'c7d17a15ac88610d013ec9ffffa9520aeb69929b',argent:'d08e52dd1e18c9f7e9a2dc482048c2db31d25611',available:await exists(join(ROOT,'.cache/upstream/silverc'))},vm:{available:await nativeVmAvailable()},sdk:'Pinned local kaspa-wasm32-sdk',port:8930};}
const utxo=(tag,amount,script,cov)=>new sdk.UtxoEntries([{outpoint:{transactionId:tag.repeat(32),index:0},amount:BigInt(amount),scriptPublicKey:script,blockDaaScore:0n,isCoinbase:false,...(cov?{covenant_id:cov}:{})}]).items[0];
const native=()=>utxo('ee',10000000000n,sdk.payToAddressScript(keys[3].toAddress('testnet-10')));
const av=v=>typeof v==='number'?{kind:'int',value:v}:{kind:'bytes',value:[...Buffer.from(v,'hex')]};
let compileQueue=Promise.resolve();
function exclusive(fn){const p=compileQueue.then(fn);compileQueue=p.catch(()=>{});return p;}
async function compileCheck(file,args,script,temp){const output=join(temp,'artifact.json'),argfile=join(temp,'args.json');await writeFile(argfile,JSON.stringify(args));await run(join(ROOT,'.cache/upstream/silverc'),[join(ROOT,file),'--constructor-args',argfile,'-o',output],{cwd:ROOT,timeout:60000,maxBuffer:1048576});const a=JSON.parse(await readFile(output)),c=Object.values(a.contracts)[0];if(Buffer.from(c.compiled.bytecode).toString('hex')!==script)throw Error('Fresh compiler output differs from configured template.');}
function exportTx(tx){return{version:tx.version,lockTime:String(tx.lockTime),storageMass:String(tx.storageMass),inputs:tx.inputs.map(i=>({transactionId:i.previousOutpoint.transactionId,index:i.previousOutpoint.index,sequence:String(i.sequence),computeBudget:i.computeBudget,signatureScript:i.signatureScript,amount:String(i.utxo.amount),scriptPublicKey:i.utxo.entry.scriptPublicKey.script,covenantId:i.utxo.entry.covenantId?.toString()||null})),outputs:tx.outputs.map(o=>({value:String(o.value),scriptPublicKey:o.scriptPublicKey.script,covenant:o.covenant?{authorizingInput:o.covenant.authorizingInput,covenantId:o.covenant.covenantId.toString()}:null}))};}
async function validateInner(example,raw,{checkTools=true}={}){
 const{definition:d,values:v}=normalize(example,raw),templates=JSON.parse(await readFile(join(ROOT,'.cache/public-templates/templates.json'))).templates,argent=JSON.parse(await readFile(join(ROOT,'src/v5-argent-templates.json'))),source=await readFile(join(ROOT,d.file),'utf8'),checks=[],compilations=[];let p,sign,summary,proofEvidence=null;
 if(example==='allowance'){
  const states=[v5ArgentInitialState({owner:owners[0],issuer:owners[2],world,operator:owners[3],resources:{crops:100}}),v5ArgentInitialState({owner:owners[1],issuer:owners[2],world,resources:{bread:100}})];states[0].allow_crops=v.allowance;states[0].min_receive=1;
  const cells=await Promise.all(states.map(async(state,i)=>{const asset=instantiateV5Argent(sdk,argent,state),id=(i?'bb':'aa').repeat(32);compilations.push({file:'contracts/public/argent-market/generated/Business.sil',args:Object.values(state).map(av),script:asset.script});return{state,utxo:utxo(i?'22':'11',100000000, sdk.payToScriptHashScript(asset.script),id),certificate:sdk.signScriptHash(await v5ArgentCertificateDigest({world,covenantId:id,owner:state.owner}),keys[2]).slice(2,-2)};}));
  p=buildV5ArgentTrade(sdk,{templates:argent,left:cells[0],right:cells[1],deltas:{crops:-v.spend,bread:v.receive},leftDelegated:true,fundingUtxos:[native()],feeRate:v.feeRate});sign=()=>signV5ArgentPlan(p,(tx,i,{owner})=>sdk.createInputSignature(tx,i,keys[owners.indexOf(owner)]));summary=`Operator spends ${v.spend} crop units for ${v.receive} bread units; allowance falls from ${v.allowance} to ${v.allowance-v.spend}. Two issuer-certified digital inventories change together.`;
 }else if(example==='receipt'){
  const build=q=>instantiatePublicReceipt(sdk,templates.receipt,{series:world,state:{owner:owners[0],quantity:q}}),r=build(v.backing),successors=v.redeem===v.backing?[]:[build(v.backing-v.redeem)];p=buildBackedMove(sdk,{receiptInputs:[{receipt:r,utxo:utxo('11',v.backing,sdk.payToScriptHashScript(r.script),'aa'.repeat(32))}],successors,operation:'redeem',sponsorUtxo:native(),sponsorPublicKey:owners[3],feeRate:v.feeRate});compilations.push({file:d.file,args:[world,3000000,owners[0],v.backing].map(av),script:r.script});sign=()=>signBackedPlan(p,(tx,i,{owner})=>sdk.createInputSignature(tx,i,keys[owners.indexOf(owner)]));summary=`Redeem ${v.redeem} fully backed units for exactly ${v.redeem} sompi; ${v.backing-v.redeem} units remain. Sponsor pays the network fee.`;
 }else{
  let state,args,entry,parameters={};if(example==='escrow'){state={buyer:owners[0],seller:owners[1],arbiter:owners[2],refundAfter:v.refundAfter,principal:v.principal,maxFee:1000000};args=[owners[0],owners[1],owners[2],v.refundAfter,v.principal,1000000].map(av);entry=v.action;parameters={paySeller:true};}else if(example==='treasury'){state={memberA:owners[0],memberB:owners[1],memberC:owners[2],principal:v.principal,maxFee:1000000};args=[...owners.slice(0,3),v.principal,1000000].map(av);entry='spend';parameters={pair:Number(v.pair),beneficiary:owners[3]};}else{state={owner:owners[0],principal:v.principal,maxFee:20000000};const generated=generateProof({owner:owners[0],taskNonce:v.nonce.toString(16).padStart(32,'0'),allocation:v.allocation,rate:v.rate,executable:join(ROOT,'scripts/v6-proof-prover/target/debug/v6-proof-prover')});const f={verifyingKey:generated.verifyingKey,proof:generated.proof,inputs:generated.publicInputs.values};args=[owners[0],f.verifyingKey,...f.inputs,v.principal,20000000].map(av);await mkdir(join(ROOT,'.cache/workbench'),{recursive:true});const proofTemp=await mkdtemp(join(ROOT,'.cache/workbench/proof-'));try{await writeFile(join(proofTemp,'args.json'),JSON.stringify(args));await run(join(ROOT,'.cache/upstream/silverc'),[join(ROOT,d.file),'--constructor-args',join(proofTemp,'args.json'),'-o',join(proofTemp,'artifact.json')],{cwd:ROOT,timeout:60000,maxBuffer:1048576});templates.proof={...templates.proof,artifact:JSON.parse(await readFile(join(proofTemp,'artifact.json'))),proofFixture:f};}finally{await rm(proofTemp,{recursive:true,force:true});}proofEvidence={circuit:generated.circuit,publicInputs:generated.publicInputs,generatedLocally:true,experimentalSetup:true};entry='verify';}
  const c=instantiatePublicContract(sdk,templates[example],state);p=buildPublicSpend(sdk,{contract:c,utxo:utxo('11',v.principal,sdk.payToScriptHashScript(c.script)),entry,parameters,pastMedianTime:v.currentMedianTime,feeRate:v.feeRate});compilations.push({file:d.file,args,script:c.script});sign=()=>signPublicPlan(p,(tx,i,{publicKey})=>sdk.createInputSignature(tx,i,keys[owners.indexOf(publicKey)]));summary=example==='proof'?`Generated a proof for A=${v.allocation}, B=${v.rate}: A×B=42 and A+B=13. Recipient and nonce ${v.nonce} are bound as public inputs. Experimental public setup; this is a fixed arithmetic circuit, not an arbitrary-work verifier.`:example==='treasury'?`Members ${[['A','B'],['A','C'],['B','C']][Number(v.pair)].join(' + ')} jointly authorize the sample beneficiary payout.`:`Construct the ${v.action} escrow path. Refund timing uses a synthetic median-time assumption, not an observed node.`;
 }
 if(example==='proof'&&v.proofVariant==='corrupt')p.args[1]=(p.args[1][0]==='0'?'1':'0')+p.args[1].slice(1);
 const unsigned=JSON.parse(p.transaction.serializeToSafeJSON());unsigned.inputs.forEach(i=>i.signatureScript='');const transaction=JSON.stringify(unsigned),mass=p.mass||publicTransactionMass(p.transaction);const inputTotal=p.transaction.inputs.reduce((n,i)=>n+i.utxo.amount,0n),outputTotal=p.transaction.outputs.reduce((n,o)=>n+o.value,0n);if(inputTotal-outputTotal!==BigInt(p.fee)||!mass.withinBlockLimits||BigInt(p.fee)<BigInt(mass.minimumFee))throw Error('Independent value or fee check failed.');checks.push({label:'Transaction construction',kind:'modeled',ok:true,detail:'Actual pinned SDK builder; synthetic UTXOs and public disposable fixture identities. No RPC, real signing key or broadcast.'},{label:'Amounts and policy',kind:'validation',ok:true,detail:'Bounds, conservation, successor scripts and required signature roles checked by the builder.'});
 await mkdir(join(ROOT,'.cache/workbench'),{recursive:true});const temp=await mkdtemp(join(ROOT,'.cache/workbench/run-'));let vm=false;
 try{
  if(checkTools&&await exists(join(ROOT,'.cache/upstream/silverc'))){for(const c of compilations)await compileCheck(c.file,c.args,c.script,temp);checks.push({label:'Fresh compilation',kind:'compiler',ok:true,detail:'Configured state matches freshly compiled SilverScript byte-for-byte.'});}else checks.push({label:'Fresh compilation',kind:'compiler',ok:null,detail:'Not run: compiler unavailable or disabled. Using pinned compiled templates.'});
  if(checkTools&&await nativeVmAvailable()){await sign();if(example==='treasury'&&v.authorization==='missing-second'){const tx=p.transaction;tx.inputs[0].signatureScript=tx.inputs[0].signatureScript.slice(0,134)+'00'.repeat(65)+tx.inputs[0].signatureScript.slice(264);}await writeFile(join(temp,'transaction.json'),JSON.stringify(exportTx(p.transaction)));const upstream=join(ROOT,'.cache/upstream/silverscript'),vmExecutable=process.env.WORKBENCH_VM_EXECUTABLE;if(!vmExecutable){const runner=await readFile(join(ROOT,'developer-workbench/export-template/runner.rs')),target=join(upstream,'silverscript-lang/tests/kaspa_workbench.rs');if(!await exists(target)||!(await readFile(target)).equals(runner))await writeFile(target,runner);}let r;try{r=await run(vmExecutable||'cargo',vmExecutable?['--nocapture']:['test','-p','silverscript-lang','--test','kaspa_workbench','--locked','--offline','--','--nocapture'],{cwd:vmExecutable?ROOT:upstream,env:{...process.env,WORKBENCH_FIXTURE:join(temp,'transaction.json')},timeout:120000,maxBuffer:2097152});}catch(e){const reason=e.stdout?.match(/WORKBENCH_VM_REJECTED[^\n]*/)?.[0];throw Object.assign(Error(reason?'Native VM rejected this configured transaction: '+reason.replace('WORKBENCH_VM_REJECTED ',''):'Native VM could not run. Check the installed offline Rust toolchain.'),{stage:'vm',checks});}if(!r.stdout.includes('WORKBENCH_VM_OK'))throw Error('Native VM returned no success marker.');vm=true;checks.push({label:'Native VM execution',kind:'vm',ok:true,detail:'This configured transaction executed with disposable fixture signatures. A mutated unlocking script was rejected. '+r.stdout.match(/WORKBENCH_VM_OK[^\n]*/)[0]});}else checks.push({label:'Native VM execution',kind:'vm',ok:null,detail:'Not run: native toolchain unavailable or disabled. Structural validation is not VM evidence.'});
 }finally{await rm(temp,{recursive:true,force:true});}
 return{ok:true,stage:vm?'vm':'validation',example,values:v,network:'testnet-10',synthetic:true,submitted:false,checks,summary,source,sourcePath:d.file,sourceHash:hash(source),transaction,fee:{sompi:p.fee,kas:Number(p.fee)/1e8,mass},inputs:p.transaction.inputs.map((i,n)=>({label:`Input ${n+1}`,amount:String(i.utxo.amount),detail:i.utxo.entry.covenantId?'Synthetic covenant output':'Synthetic script output',outpoint:{transactionId:i.previousOutpoint.transactionId,index:i.previousOutpoint.index}})),outputs:p.transaction.outputs.map((o,n)=>({label:`Output ${n+1}`,amount:String(o.value),detail:o.covenant?'Constrained successor':'Native payout or change',scriptPublicKey:o.scriptPublicKey.script})),applicationTemplate:example==='allowance'?argent:templates[example],compilerInputs:compilations.map(c=>({file:c.file,constructorArgs:c.args,configuredScriptSha256:hash(c.script)})),proof:proofEvidence,state:p.states||p.contract?.state||null};
}
export async function validate(example,values,options){return exclusive(async()=>{try{return await validateInner(example,values,options);}catch(e){return{ok:false,stage:e.stage||'validation',example,synthetic:true,submitted:false,error:String(e.message).replace('The node median time','The synthetic median time').slice(0,700),checks:[...(e.checks||[]),{label:e.stage==='vm'?'Native VM execution':'Configuration / execution',kind:e.stage==='vm'?'vm':'validation',ok:false,detail:String(e.message).replace('The node median time','The synthetic median time').slice(0,700)}]};}});}
export async function exportProject(example,values){
 const normalized=normalize(example,values),result=await validate(example,normalized.values);if(!result.ok)throw Error(result.error);const parent=await mkdtemp(join(ROOT,'.cache/workbench/export-')),directory=join(parent,'project');await mkdir(directory,{recursive:true});
 try{
  const files=['THIRD_PARTY.md','favicon.svg','faucet/policy.mjs','LICENSE.md','licenses/PolyForm-Noncommercial-1.0.0.md','src/public-contracts.mjs','src/public-receipt.mjs','src/public-asset-signing.mjs','src/v5-argent-protocol.mjs','src/v6-proof-protocol.mjs','src/v6-proof-core.mjs','scripts/v6-proof-prover/target/debug/v6-proof-prover','scripts/v6-proof-prover/Cargo.toml','scripts/v6-proof-prover/Cargo.lock','scripts/v6-proof-prover/src/lib.rs','scripts/v6-proof-prover/src/main.rs','src/v5-argent-templates.json','.cache/public-templates/templates.json','developer-workbench/engine.mjs','developer-workbench/server.mjs','developer-workbench/export-template/runner.rs',...defs.map(d=>d.file),'contracts/public/argent-market/generated/Business.sil','.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa/kaspa.js','.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa/kaspa_bg.wasm','.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa/package.json','.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa/LICENSE'];
  if(await exists(join(ROOT,'.cache/upstream/silverc')))files.push('.cache/upstream/silverc');
  for(const path of files){await mkdir(dirname(join(directory,path)),{recursive:true});await copyFile(join(ROOT,path),join(directory,path));}
  for(const path of ['index.html','app.mjs','styles.css'])await copyFile(join(ROOT,'developer-workbench/export-template',path),join(directory,'developer-workbench',path));
  for(const[name,path]of[['SilverScript-LICENSE','.cache/upstream/silverscript/LICENSE'],['Argent-LICENSE','.cache/upstream/argent/LICENSE']])if(await exists(join(ROOT,path))){await mkdir(join(directory,'licenses'),{recursive:true});await copyFile(join(ROOT,path),join(directory,'licenses',name));}
  await cp(join(ROOT,'developer-workbench/export-template/third-party'),join(directory,'licenses/third-party'),{recursive:true});
  await writeFile(join(directory,'application.mjs'),(await readFile(join(ROOT,'developer-workbench/export-template/application.mjs'),'utf8')).replaceAll("from '../../src/","from './src/"));
  const config={example,values:normalized.values};await writeFile(join(directory,'config.json'),JSON.stringify(config,null,2));await writeFile(join(directory,'validation.json'),JSON.stringify(result,null,2));await writeFile(join(directory,'application-template.json'),JSON.stringify(result.applicationTemplate,null,2));await writeFile(join(directory,'compiler-inputs.json'),JSON.stringify(result.compilerInputs,null,2));await writeFile(join(directory,'developer-workbench/config.json'),JSON.stringify(config));
  await writeFile(join(directory,'package.json'),JSON.stringify({name:'kaspa-'+example+'-starter',private:true,type:'module',engines:{node:'>=22'},scripts:{start:'node start.mjs',test:'node --test starter.test.mjs',check:'node check.mjs'}},null,2));
  await writeFile(join(directory,'start.mjs'),"process.env.WORKBENCH_PORT ||= '8931';const{createWorkbenchServer}=await import('./developer-workbench/server.mjs');const port=Number(process.env.WORKBENCH_PORT);createWorkbenchServer({allowFaucet:false}).listen(port,'127.0.0.1',()=>console.log('Application starter: http://127.0.0.1:'+port));\n");
  await writeFile(join(directory,'check.mjs'),"import{readFile,writeFile}from'node:fs/promises';import{validate}from'./developer-workbench/engine.mjs';const c=JSON.parse(await readFile('config.json'));const r=await validate(c.example,c.values);await writeFile('validation.json',JSON.stringify(r,null,2));console.log(JSON.stringify(r,null,2));if(!r.ok)process.exitCode=1;\n");
  await writeFile(join(directory,'starter.test.mjs'),"import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{validate}from'./developer-workbench/engine.mjs';test('configured unsigned transaction conserves value and rejects unknown fields',async()=>{const c=JSON.parse(await readFile('config.json')),r=await validate(c.example,c.values,{checkTools:false});assert.equal(r.ok,true,r.error);assert.equal(r.submitted,false);const tx=JSON.parse(r.transaction);assert(tx.inputs.every(i=>i.signatureScript===''));assert.equal(r.inputs.reduce((n,i)=>n+BigInt(i.amount),0n)-r.outputs.reduce((n,o)=>n+BigInt(o.amount),0n),BigInt(r.fee.sompi));assert.equal((await validate(c.example,{...c.values,unexpected:true},{checkTools:false})).ok,false);});\n");
  await writeFile(join(directory,'README.md'),`# ${normalized.definition.title} application starter\n\nThis is an offline Testnet-10 developer beta using synthetic UTXOs and public disposable fixture identities. Never fund those identities. There is no wallet, RPC or transaction submission endpoint.\n\nRun with Node.js 22 or later:\n\n\`\`\`sh\nnpm test\nnpm start\n# Open http://127.0.0.1:8931\n# Stop the server, edit config.json, then:\nnpm run check\n\`\`\`\n\nNo package installation is required: the pinned SDK JavaScript/WASM runtime is included. The included silverc executable was built for ${process.platform}/${process.arch}; it is optional for construction and must be replaced with the pinned revision when using another platform. Compiler/tool availability is reported, and missing native VM tooling is never marked passed.\n\nThe selected configuration is in config.json; the complete unsigned transaction and validation evidence are in validation.json. The UI allows bounded configuration of the included examples. Application sources are in contracts/public; browser-independent transaction builders are in src. ${example==='proof'?'Proof payout generates a bounded arithmetic proof with A×B=42 and A+B=13 using the included local prover. Recipient and nonce are bound as public inputs. The setup is public/experimental and unsuitable for production; this is not an arbitrary-work verifier.':''}\n\nThis export includes the native VM test adapter, not the multi-gigabyte Rust dependencies. The original workbench ran the exact configured transaction and rejected a corrupted unlocking script using native covenant VM execution. To repeat that stage independently, obtain SilverScript revision c7d17a15ac88610d013ec9ffffa9520aeb69929b and its locked dependencies at .cache/upstream/silverscript. A Rust toolchain and populated Cargo cache are required; the check runs offline and fails rather than fetching missing dependencies. Argent source provenance is d08e52dd1e18c9f7e9a2dc482048c2db31d25611; the allowance example recompiles its generated SilverScript when silverc is available.\n\nOriginal project license: LICENSE.md and licenses/PolyForm-Noncommercial-1.0.0.md. Project code is noncommercial; commercial use requires separate permission. Required Notice: Copyright (c) 2026 Kaspa Explained. https://kaspaexplained.com/. Bundled SDK license: .cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa/LICENSE. Compiler and Argent licenses: licenses/. Bundled Rust dependency notices and inventory: licenses/third-party/. This is not an audited or deployed production application.\n`);
  await writeFile(join(directory,'INTEGRATION.md'),`# Connect caller-owned inputs

application.mjs is the public integration boundary. It accepts the caller's SDK, public keys, known compiled template and SDK UTXO references. It has no fixture signing keys, RPC calls, signing or submission. The offline UI is a separate sandbox.

For escrow, obtain the UTXO from your selected Testnet-10 node, resolve its output against the compiled contract address, then construct:

\`\`\`js
import {buildApplication} from './application.mjs';
const result = buildApplication({
  sdk, example: 'escrow', template,
  participants: {buyer: buyerPublicKey, seller: sellerPublicKey, arbiter: arbiterPublicKey},
  values: {principal: 50000000, refundAfter: refundUnixMilliseconds,
    currentMedianTime: nodePastMedianTime, action: 'release', feeRate: 100},
  cell: {utxo: observedSdkUtxo}
});
// result.transaction is unsigned safe JSON. Review output recipients, amounts,
// fees, required signers and network before giving result.plan to a wallet.
\`\`\`

The builder rejects an observed script or principal that differs from the supplied policy. UTXO metadata must come from the chosen node rather than an untrusted browser request. The library checks construction; it does not establish chain acceptance or independently query whether an input remains unspent.

Other examples:

- Treasury: participants memberA/memberB/memberC/beneficiary; values principal/pair/feeRate. All addresses are derived from caller public keys.
- Receipt: participants holder/sponsor/series, values backing/redeem/feeRate, cell.utxo, and exactly one native feeUtxos entry. The observed covenant retains its identity and backing.
- Allowance: use the full Argent template bundle, cell and peer each containing an observed state, utxo and independently issued certificate; values allowance/spend/receive/feeRate; caller-owned feeUtxos. This function never issues certificates.
- Proof: use a template freshly compiled for the generated proof's verifying key and public inputs, participants.owner, proofBundle, values principal/feeRate and cell.utxo. proofBundle.owner and exact inputs must match. A different recipient or nonce requires a fresh proof/template; the included public experimental setup is not suitable for production.

The bundled SDK exposes transaction/wallet helpers. This starter deliberately leaves wallet authorization, network synchronization, persistent acceptance tracking and production setup to the integrating application. It never uses the offline engine's sample identities in application.mjs.
`);
  await writeFile(join(directory,'provenance.json'),JSON.stringify({network:'testnet-10',example,sourceHashes:Object.fromEntries(await Promise.all(files.map(async path=>[path,hash(await readFile(join(directory,path)))]))),compilerPlatform:process.platform+'/'+process.arch,validationStage:result.stage,synthetic:true,submitted:false},null,2));
  const zip=join(parent,'starter.zip');await run('/usr/bin/zip',['-q','-r',zip,'.'],{cwd:directory,timeout:60000,maxBuffer:1048576});return{filename:`kaspa-${example}-starter.zip`,bytes:await readFile(zip)};
 }finally{await rm(parent,{recursive:true,force:true});}
}
