import {createRequire} from 'node:module';
import {validateClaim} from '../faucet/policy.mjs';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {catalog,health,validate,ROOT} from './engine.mjs';
const faucetSdk=createRequire(import.meta.url)('../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa');
const root=resolve(ROOT,'developer-workbench'),types={'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
export function createWorkbenchServer({allowFaucet=true,publicOrigin=null}={}){if(publicOrigin){allowFaucet=false;if(publicOrigin!=='https://kaspaexplained.com')throw Error('Public origin must be the exact HTTPS origin https://kaspaexplained.com.');}return createServer(async(req,res)=>{const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));};try{if(publicOrigin&&process.env.WORKBENCH_LEASE_EXPIRES_AT&&Date.now()>=Number(process.env.WORKBENCH_LEASE_EXPIRES_AT))return json({error:'Studio runtime lease ended.'},503);const host=req.headers.host,port=String(req.socket.localPort);if(publicOrigin?host!==new URL(publicOrigin).host:host!==`127.0.0.1:${port}`&&host!==`localhost:${port}`)return json({error:'Loopback host required.'},403);const origin=publicOrigin||'http://'+host;const url=new URL(req.url,origin);if(req.method==='POST'){if(req.headers.origin&&req.headers.origin!==origin||req.headers['sec-fetch-site']==='cross-site')return json({error:'Same-origin request required.'},403);if(!req.headers['content-type']?.startsWith('application/json'))return json({error:'JSON required.'},415);let chunks=[],bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>16384)return json({error:'Request too large.'},413);chunks.push(chunk);}let body;try{body=JSON.parse(Buffer.concat(chunks).toString());}catch{return json({error:'Malformed JSON.'},400);}if(!body||Array.isArray(body)||typeof body!=='object')return json({error:'Object required.'},400);
 if(url.pathname==='/api/faucet'){if(!allowFaucet)return json({error:'Faucet unavailable in the offline starter.'},404);const claim=validateClaim(body,faucetSdk);const upstream=await fetch('https://kaspa-demo-faucet.parker2017.workers.dev/api/faucet',{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://127.0.0.1:8912'},body:JSON.stringify(claim),signal:AbortSignal.timeout(20000)});const result=await upstream.json();return json(result,upstream.status);}
 if(url.pathname==='/api/validate'||url.pathname==='/api/export'){if(Object.keys(body).some(k=>!['example','values'].includes(k)))return json({error:'Unexpected request fields.'},400);if(url.pathname==='/api/validate'){const result=await validate(body.example,body.values);return json(result,result.ok?200:400);}const{exportProject}=await import('./engine.mjs');const result=await exportProject(body.example,body.values);res.writeHead(200,{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${result.filename}"`,'Cache-Control':'no-store'});return res.end(result.bytes);}
 if(['/api/argent','/api/krc'].includes(url.pathname)){const tools=await import('./ecosystem-tools.mjs');return json(url.pathname==='/api/argent'?await tools.inspectArgent(body.example):await tools.inspectKrc(body.payload));}return json({error:'Unknown endpoint.'},404);}
 if(req.method!=='GET')return json({error:'Method not allowed.'},405);if(url.pathname==='/api/catalog')return json(catalog());if(url.pathname==='/api/health')return json(await health());if(url.pathname==='/api/argent/catalog'){const tools=await import('./ecosystem-tools.mjs');return json(await tools.argentCatalog());}
 const assets={'/LICENSE.md':'LICENSE.md','/THIRD_PARTY.md':'THIRD_PARTY.md','/favicon.svg':'favicon.svg','/assets/workbench/live-engine.mjs':'developer-workbench/live-engine.mjs','/assets/src/public-contracts.mjs':'src/public-contracts.mjs','/assets/src/public-acceptance.mjs':'src/public-acceptance.mjs','/assets/src/v6-browser-wallet.mjs':'src/v6-browser-wallet.mjs','/assets/public-templates.json':'.cache/public-templates/templates.json','/assets/kaspa/kaspa.js':'.cache/upstream/kaspa-wasm32-sdk/web/kaspa/kaspa.js','/assets/kaspa/kaspa_bg.wasm':'.cache/upstream/kaspa-wasm32-sdk/web/kaspa/kaspa_bg.wasm'};if(assets[url.pathname]){const path=assets[url.pathname],content=await readFile(resolve(ROOT,path));res.writeHead(200,{'Content-Type':path.endsWith('.md')?'text/plain; charset=utf-8':path.endsWith('.svg')?'image/svg+xml':path.endsWith('.wasm')?'application/wasm':path.endsWith('.json')?'application/json':'text/javascript; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});return res.end(content);}
 const paths={'/':'index.html','/live-ui.mjs':'live-ui.mjs','/capabilities.json':'capabilities.json','/legibility-research.md':'legibility-research.md','/index.html':'index.html','/app.mjs':'app.mjs','/styles.css':'styles.css','/config.json':'config.json','/ecosystem.json':'ecosystem.json','/research.md':'research.md'};const name=paths[url.pathname];if(!name)return json({error:'Not found.'},404);const data=await readFile(resolve(root,name));res.writeHead(200,{'Content-Type':types[name.slice(name.lastIndexOf('.'))]||'text/plain; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' wss://muon-10.kaspa.blue; frame-ancestors 'none'; base-uri 'none'"});res.end(data);
 }catch(e){json({ok:false,error:String(e.message).slice(0,700)},400);}});}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const publicOrigin=process.env.WORKBENCH_PUBLIC_ORIGIN||null;const server=createWorkbenchServer({publicOrigin,allowFaucet:!publicOrigin});const port=Number(process.env.WORKBENCH_PORT||8930);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Invalid loopback port.');server.listen(port,publicOrigin?'0.0.0.0':'127.0.0.1',()=>console.log('Developer workbench: http://127.0.0.1:'+port));}
