[package]
name = "v6-proof-prover"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "v6-proof-prover"
path = "src/main.rs"

[dependencies]
ark-bn254 = "=0.6.0"
ark-crypto-primitives = { version = "=0.6.0", default-features = false, features = ["snark", "sponge", "std"] }
ark-ff = "=0.6.0"
ark-groth16 = "=0.6.0"
ark-relations = "=0.6.0"
ark-serialize = "=0.6.0"
ark-snark = "=0.6.0"
ark-std = "=0.6.0"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

