#!/usr/bin/env python3
"""Reading-grade gate.

Owner brief, 1 Aug 2026: two real buyers read a page written by this project and
could not tell what was being sold. The cause was word choice, not sentence
length. So this measures grade, and it measures it separately for the copy
everyone reads and the copy one specialist audience reads.

Shared copy is the hero, the method, the workflow, the contact block: anything a
first-time visitor meets. It is held to grade 9. Specialist blocks carry their
own field's vocabulary and are exempt, because plain-languaging them makes them
wrong.

Mark a specialist block in HTML with data-audience="specialist". Everything else
in <main> is shared.

Usage:
  python3 scripts/check-reading-grade.py [files...]     # default: every page
  python3 scripts/check-reading-grade.py --worst FILE   # show the heaviest lines
"""
import sys, re, json, pathlib, html

try:
    import textstat
except ImportError:
    sys.exit("textstat not installed. Run: python3 -m pip install textstat")

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHARED_MAX = 9.0
# Pages that are reference material for people who already know the field. They
# still get measured and reported; they just do not fail the gate.
EXEMPT = {
    "glossary.html", "sources.html", "ai-guidance.html", "kaspa-claims-checker.html",
    "argent-explained.html", "kips.html",
}

BLOCK = re.compile(r"<(p|li|h1|h2|h3|figcaption|td|th)\b[^>]*>(.*?)</\1>", re.S | re.I)
SPECIALIST = re.compile(r'data-audience\s*=\s*"specialist"', re.I)
STRIP = re.compile(r"<[^>]+>")
DROP = re.compile(r"<(script|style|svg|nav|header|footer)\b.*?</\1>", re.S | re.I)
# The related-links block is generated by scripts/apply-related-links.py from
# OTHER pages' meta descriptions. Measuring it here made every page's grade
# depend on other pages' <head>, and no local edit could fix it because the
# next build overwrites the block. Each description is measured once, at its
# source, by --descriptions instead.
GENERATED = re.compile(r"<!--\s*related-links:start\s*-->.*?<!--\s*related-links:end\s*-->", re.S | re.I)


def main_of(src: str) -> str:
    m = re.search(r"<main\b[^>]*>(.*?)</main>", src, re.S | re.I)
    return m.group(1) if m else ""


def specialist_spans(body: str):
    """Byte ranges of elements carrying data-audience="specialist"."""
    spans = []
    for m in re.finditer(r"<(\w+)[^>]*data-audience\s*=\s*\"specialist\"[^>]*>", body, re.I):
        tag, start = m.group(1), m.start()
        depth, i = 0, m.start()
        pat = re.compile(rf"</?{tag}\b", re.I)
        for t in pat.finditer(body, m.start()):
            depth += -1 if body[t.start():t.start() + 2] == "</" else 1
            if depth == 0:
                spans.append((start, t.end()))
                break
    return spans


def texts(path: pathlib.Path):
    src = path.read_text(encoding="utf-8")
    src = GENERATED.sub(" ", DROP.sub(" ", src))
    body = main_of(src)
    spans = specialist_spans(body)

    def is_specialist(pos):
        return any(a <= pos < b for a, b in spans)

    shared, spec = [], []
    for m in BLOCK.finditer(body):
        raw = html.unescape(STRIP.sub(" ", m.group(2)))
        txt = re.sub(r"\s+", " ", raw).strip()
        if len(txt.split()) < 4:
            continue
        (spec if is_specialist(m.start()) else shared).append(txt)
    return shared, spec


def grade(lines):
    if not lines:
        return None
    joined = " ".join(lines)
    return dict(
        fk=round(textstat.flesch_kincaid_grade(joined), 1),
        fog=round(textstat.gunning_fog(joined), 1),
        ease=round(textstat.flesch_reading_ease(joined), 1),
        words=len(joined.split()),
    )


DESC = re.compile(r'<meta\s+name="description"\s+content="([^"]*)"', re.I)


def descriptions(files):
    """Every page's own meta description, measured once. These strings are
    reused as card copy across the site by apply-related-links.py, so a heavy
    one shows up on many pages at once."""
    rows = []
    for f in files:
        m = DESC.search(f.read_text(encoding="utf-8"))
        if not m or len(m.group(1).split()) < 5:
            continue
        rows.append((round(textstat.flesch_kincaid_grade(m.group(1)), 1), f.name, m.group(1)))
    rows.sort(reverse=True)
    over = [r for r in rows if r[0] > SHARED_MAX]
    print(f"{'page':40s} {'FK':>5s}  description")
    print("-" * 96)
    for g, n, d in rows:
        flag = "  OVER" if g > SHARED_MAX else ""
        print(f"{n[:40]:40s} {g:5.1f}  {d[:52]}{flag}")
    print(f"\n{len(rows)} descriptions, {len(over)} over grade {SHARED_MAX}.")
    return 1 if over else 0


def worst(path):
    shared, _ = texts(path)
    scored = sorted(
        ((textstat.flesch_kincaid_grade(t), t) for t in shared if len(t.split()) >= 8),
        reverse=True,
    )
    print(f"\nHeaviest shared lines in {path.name}\n" + "=" * 78)
    for g, t in scored[:12]:
        print(f"  FK {g:5.1f}  {t[:150]}")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if "--descriptions" in sys.argv:
        files = [pathlib.Path(a) for a in args] if args else sorted(ROOT.glob("*.html"))
        return descriptions([f for f in files if f.exists()])
    if "--worst" in sys.argv:
        for a in args:
            worst(pathlib.Path(a) if pathlib.Path(a).exists() else ROOT / a)
        return 0

    files = [pathlib.Path(a) for a in args] if args else sorted(ROOT.glob("*.html"))
    rows, failures = [], []
    for f in files:
        if not f.exists():
            f = ROOT / f.name
        shared, spec = texts(f)
        gs, gp = grade(shared), grade(spec)
        if not gs:
            continue
        exempt = f.name in EXEMPT
        bad = gs["fk"] > SHARED_MAX and not exempt
        if bad:
            failures.append((f.name, gs["fk"]))
        try:
            label = str(f.resolve().relative_to(ROOT))
        except ValueError:
            label = f.name
        rows.append((label, gs, gp, exempt, bad))

    rows.sort(key=lambda r: -r[1]["fk"])
    print(f"{'page':44s} {'shared FK':>9s} {'fog':>5s} {'ease':>6s} {'words':>6s}  {'specialist':>10s}")
    print("-" * 92)
    for name, gs, gp, exempt, bad in rows:
        flag = "  FAIL" if bad else ("  (reference)" if exempt else "")
        sp = f"{gp['fk']}" if gp else "-"
        print(f"{name[:44]:44s} {gs['fk']:9.1f} {gs['fog']:5.1f} {gs['ease']:6.1f} {gs['words']:6d}  {sp:>10s}{flag}")

    json.dump([dict(file=n, shared=gs, specialist=gp, exempt=e) for n, gs, gp, e, _ in rows],
              open("/tmp/reading-grade.json", "w"), indent=1)
    print(f"\nPages: {len(rows)}   over grade {SHARED_MAX}: {len(failures)}")
    if failures:
        print("Rewrite with shorter words. Do not shorten sentences; that is not the cause.")
        for n, g in failures:
            print(f"  {n} at {g}")
        return 1
    print("Reading grade OK.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
