// Isolated live-UI acceptance. Creates an unfunded disposable wallet only.
// Faucet requests are blocked; this runner never approves or submits a transaction.
import {chromium, firefox, webkit} from 'playwright';
import {auditPage} from './browser.mjs';
import assert from 'node:assert/strict';
import {mkdir, writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const out=resolve('.cache/developer-workbench-browser');
await mkdir(resolve(out,'downloads'),{recursive:true});
async function ownershipAcceptance(){
const reports=[];
const open=async p=>{await p.goto('http://127.0.0.1:8930');await p.locator('[data-action=live]').waitFor({state:'attached'});if(!await p.locator('[data-action=live]').isVisible())await p.locator('[data-action=menu]').click();await p.locator('[data-action=live]').click();await p.locator('[data-live=create]').waitFor();};
for(const[name,type]of Object.entries({chromium,firefox,webkit})){const b=await type.launch();for(const width of [1440,390]){const c=await b.newContext({viewport:{width,height:844},acceptDownloads:true});const errors=[],requests=[];await c.route('**/api/faucet',r=>{requests.push('FORBIDDEN faucet');return r.abort();});c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));const p=await c.newPage();let r={name,width,errors,requests};reports.push(r);try{await open(p);await p.locator('[data-live=create]:not([disabled])').waitFor();r.audit=await auditPage(p);const other=await c.newPage();await open(other);await other.getByRole('alert').filter({hasText:'already open in another tab'}).waitFor();assert(await other.locator('[data-live=create]').isDisabled());await p.close();await other.reload();await other.locator('[data-action=live]').waitFor({state:'attached'});if(!await other.locator('[data-action=live]').isVisible())await other.locator('[data-action=menu]').click();await other.locator('[data-action=live]').click();await other.locator('[data-live=create]:not([disabled])').waitFor();r.lockTransfer=true;await other.screenshot({path:`${out}/live-${name}-${width}.png`,fullPage:true});console.log(name,width,'passed');}catch(e){r.error=e.message;console.log(name,width,'FAILED',e.message)}await c.close();}await b.close();}await writeFile(`${out}/live-unfunded-report.json`,JSON.stringify(reports,null,2));

assert(reports.every(r=>!r.error&&!r.errors.length&&!r.requests.length&&!r.audit.horizontalOverflow&&!r.audit.unnamed.length&&!r.audit.contrast.length),'Fresh live view / ownership checks failed');

}
async function recoveryAcceptance(){
const b=await chromium.launch();const c=await b.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const forbidden=[],errors=[];await c.route('**/api/faucet',r=>{forbidden.push('faucet');return r.abort();});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8930');await p.locator('[data-action=live]').click();await p.locator('[data-live=create]:not([disabled])').waitFor();await p.locator('[data-live=create]').click();await p.locator('[data-live=backup]:not([disabled])').waitFor({timeout:90000});assert(await p.locator('[data-live=fund]').isDisabled());await p.locator('#live-password').fill('isolated-qa-password-2026');const d=p.waitForEvent('download');await p.locator('[data-live=backup]').click();const f=await d;const backup=`${out}/downloads/unfunded-recovery.json`;await f.saveAs(backup);const before=await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('kaspa-studio-live:')));await p.reload();await p.locator('[data-action=live]').click();await p.locator('[data-live=backup]:not([disabled])').waitFor({timeout:90000});assert(await p.locator('[data-live=fund]').isDisabled());await p.evaluate(()=>{const keys=Object.keys(localStorage).filter(k=>k.startsWith('kaspa-studio-live:'));for(const k of keys)if(k.includes('secret'))localStorage.removeItem(k);});await p.reload();await p.locator('[data-action=live]').click();await p.locator('[data-live=restore]:not([disabled])').waitFor();await p.locator('#live-password').fill('wrong-password');await p.locator('#live-recovery-file').setInputFiles(backup);await p.getByRole('alert').waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('kaspa-studio-live:active')),null);await p.locator('#live-password').fill('isolated-qa-password-2026');await p.locator('#live-recovery-file').setInputFiles(backup);await p.getByRole('status').filter({hasText:'Wallet restored into a new local record'}).waitFor({timeout:90000});assert(await p.locator('[data-live=fund]').isDisabled());const after=await p.evaluate(()=>({active:localStorage.getItem('kaspa-studio-live:active'),keys:Object.keys(localStorage).filter(k=>k.startsWith('kaspa-studio-live:'))}));assert(after.active?.startsWith('kaspa-studio-live:restored:'));assert(before.filter(k=>!k.includes('secret')).every(k=>after.keys.includes(k)));await writeFile(`${out}/live-recovery-report.json`,JSON.stringify({unfunded:true,backup:true,reload:true,wrongPasswordRetained:true,corruptLocalRecovery:true,oldRecordsPreserved:true,forbidden,errors},null,2));assert.deepEqual(forbidden,[]);assert.deepEqual(errors,[]);console.log('recovery passed');await b.close();

}
await ownershipAcceptance();
await recoveryAcceptance();
