import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{createRequire}from'node:module';import{createLiveEngine}from'../live-engine.mjs';
const sdk=createRequire(import.meta.url)('../../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa'),template=JSON.parse(await readFile(new URL('../../.cache/public-templates/templates.json',import.meta.url))).templates.escrow,keys=[61,62,63].map(n=>new sdk.PrivateKey(n.toString(16).repeat(32))),owners=keys.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()),addresses=keys.map(k=>k.toAddress('testnet-10').toString()),clone=x=>structuredClone(x),block='bb'.repeat(32),checkpoint='aa'.repeat(32);
async function fixture(){let saved=null,failSave=false,failAfterSend=false,loseReply=false,badReply=false,wrongNetwork=false,feeRate=100,median=1800000000000,signCalls=0,signMutation=false,entries=new sdk.UtxoEntries([{outpoint:{transactionId:'11'.repeat(32),index:0},amount:1000000000n,scriptPublicKey:sdk.payToAddressScript(keys[0].toAddress('testnet-10')),blockDaaScore:1n,isCoinbase:false}]).items;const sent=[],accepted=[];
 const wallet={address:addresses[0],publicKey:owners[0],async signInput(tx,i,{publicKey}){signCalls++;if(signMutation)tx.outputs[0].scriptPublicKey=sdk.payToAddressScript(keys[2].toAddress('testnet-10'));return sdk.createInputSignature(tx,i,keys[owners.indexOf(publicKey)]);}};
 const save=async data=>{if(failSave||failAfterSend&&sent.length)throw Error('Storage failed');saved=clone(data);};
 const rpc={async getServerInfo(){return{networkId:wrongNetwork?'mainnet':'testnet-10',isSynced:true,hasUtxoIndex:true};},async getBlockDagInfo(){return{network:'testnet-10',pastMedianTime:BigInt(median)};},async getFeeEstimate(){return{estimate:{priorityBucket:{feerate:feeRate}}};},async getUtxosByAddresses(addrs){const scripts=addrs.map(a=>sdk.payToAddressScript(new sdk.Address(a)).script);return{entries:entries.filter(e=>scripts.includes(e.entry.scriptPublicKey.script))};},async getSink(){return{sink:checkpoint};},async submitTransaction({transaction:tx}){assert.equal(saved.pending.transaction,tx.serializeToSafeJSON());assert.equal(saved.pending.attempts,sent.filter(t=>t.id===tx.id).length+1);assert.match(saved.pending.signedHash,/^[a-f0-9]{64}$/);sent.push(tx);if(loseReply)throw Error('Reply lost');return{transactionId:badReply?'ff'.repeat(32):tx.id};},async getVirtualChainFromBlock({startHash}){return{removedChainBlockHashes:[],addedChainBlockHashes:[],acceptedTransactionIds:startHash===checkpoint?accepted.map(id=>({acceptingBlockHash:block,acceptedTransactionIds:[id]})):[]};}};
 const opts={sdk,wallet,rpc,save,template};let engine=await createLiveEngine(opts);
 return{get engine(){return engine;},get saved(){return saved;},sent,get signCalls(){return signCalls;},flags(v){if('failSave'in v)failSave=v.failSave;if('failAfterSend'in v)failAfterSend=v.failAfterSend;if('loseReply'in v)loseReply=v.loseReply;if('badReply'in v)badReply=v.badReply;if('wrongNetwork'in v)wrongNetwork=v.wrongNetwork;if('feeRate'in v)feeRate=v.feeRate;if('median'in v)median=v.median;if('signMutation'in v)signMutation=v.signMutation;},removeInputs(){entries=[];},async restart(snapshot=saved){engine=await createLiveEngine({...opts,snapshot});return engine;},accept(){const tx=sent.at(-1);if(!accepted.includes(tx.id))accepted.push(tx.id);const inputs=new Set(tx.inputs.map(i=>i.previousOutpoint.transactionId+':'+i.previousOutpoint.index));entries=entries.filter(e=>!inputs.has(e.outpoint.transactionId+':'+e.outpoint.index));entries.push(...new sdk.UtxoEntries(tx.outputs.map((o,i)=>({outpoint:{transactionId:tx.id,index:i},amount:o.value,scriptPublicKey:o.scriptPublicKey,blockDaaScore:1n,isCoinbase:false}))).items);},reorg(){accepted.length=0;}};
}
const fund={action:'fund',terms:{principalSompi:'50000000',sellerPublicKey:owners[1],arbiterPublicKey:owners[2],refundDelayMs:60000}};
test('live escrow requires explicit review/sign, records bytes before send and rechecks acceptance after reload',async()=>{const f=await fixture(),r=await f.engine.prepare(fund);assert.equal(f.sent.length,0);assert.equal(f.signCalls,0);assert.equal(r.requiresApproval,true);await f.engine.confirm(r.id);assert.equal(f.sent.length,1);await f.engine.check();assert.equal(f.engine.status().stage,'pending');f.accept();await f.engine.check();assert.equal(f.engine.status().stage,'funded');await f.restart();assert.equal(f.engine.status().stage,'checking');await f.engine.check();assert.equal(f.engine.status().stage,'funded');const release=await f.engine.prepare({action:'release'});await f.engine.confirm(release.id);f.accept();await f.engine.check();assert.equal(f.engine.status().stage,'complete');assert.equal(f.engine.status().receipts.length,2);assert.equal(f.sent[1].outputs[0].scriptPublicKey.script,sdk.payToAddressScript(keys[1].toAddress('testnet-10')).script);await f.restart();await f.engine.check();assert.equal(f.engine.status().stage,'complete');assert.equal(f.sent.length,2);f.reorg();await f.restart();await f.engine.check();assert.equal(f.engine.status().stage,'checking');assert(f.engine.status().receipts.every(r=>!r.acceptanceVerified));});
test('lost reply and wrong response ID preserve signed bytes; checking never resends; explicit retry is identical',async()=>{for(const flag of ['loseReply','badReply']){const f=await fixture(),r=await f.engine.prepare(fund);f.flags({[flag]:true});await f.engine.confirm(r.id);assert.equal(f.engine.status().pending.status,'uncertain');const bytes=f.saved.pending.transaction;await f.restart();await f.engine.check();assert.equal(f.sent.length,1);f.flags({[flag]:false});await f.engine.retry(f.saved.pending.transactionId);assert.equal(f.sent.length,2);assert.equal(f.sent[1].serializeToSafeJSON(),bytes);assert.equal(f.signCalls,1);f.accept();await f.engine.check();assert.equal(f.engine.status().stage,'funded');}});
test('network mismatch, increased fee and missing reviewed inputs reject before signing',async()=>{for(const change of ['wrongNetwork','feeRate','missing']){const f=await fixture(),r=await f.engine.prepare(fund);if(change==='missing')f.removeInputs();else f.flags({[change]:change==='feeRate'?200:true});await assert.rejects(()=>f.engine.confirm(r.id));assert.equal(f.sent.length,0);assert.equal(f.signCalls,0);}});
test('storage failure before submit prevents send; after submit preserves recoverable journal without false no-send claim',async()=>{const f=await fixture(),r=await f.engine.prepare(fund);f.flags({failSave:true});await assert.rejects(()=>f.engine.confirm(r.id),/saved transaction journal/);assert.equal(f.sent.length,0);const g=await fixture(),review=await g.engine.prepare(fund);g.flags({failAfterSend:true});await assert.rejects(()=>g.engine.confirm(review.id),/saved transaction journal/);assert.equal(g.sent.length,1);assert.equal(g.saved.pending.attempts,1);g.flags({failAfterSend:false});g.accept();await g.restart();await g.engine.check();assert.equal(g.engine.status().stage,'funded');});
test('signer output mutation and stale or tampered saved reviews cannot submit',async()=>{const f=await fixture(),r=await f.engine.prepare(fund);f.flags({signMutation:true});await assert.rejects(()=>f.engine.confirm(r.id),/changed the reviewed/);assert.equal(f.sent.length,0);const g=await fixture(),review=await g.engine.prepare(fund),saved=clone(g.saved);saved.review.createdAt-=121000;await g.restart(saved);await assert.rejects(()=>g.engine.confirm(review.id),/stored review changed/);assert.equal(g.sent.length,0);});
test('refund observes real RPC median time and saved signed-byte corruption fails closed',async()=>{const f=await fixture(),r=await f.engine.prepare(fund);await f.engine.confirm(r.id);f.accept();await f.engine.check();await assert.rejects(()=>f.engine.prepare({action:'refund'}),/median time/);f.flags({median:1800000060000});const refund=await f.engine.prepare({action:'refund'});assert.equal(JSON.parse(refund.transaction).lockTime,'1800000060000');await f.engine.confirm(refund.id);const corrupt=clone(f.saved),tx=sdk.Transaction.deserializeFromSafeJSON(corrupt.pending.transaction);tx.inputs[0].signatureScript='00';corrupt.pending.transaction=tx.serializeToSafeJSON();await f.restart(corrupt);await assert.rejects(()=>f.engine.check(),/signed transaction bytes changed/);assert.equal(f.sent.length,2);});

test('genuinely expired review rejects before signing',async()=>{const f=await fixture(),r=await f.engine.prepare(fund),now=Date.now;try{Date.now=()=>r.createdAt+120001;await assert.rejects(()=>f.engine.confirm(r.id),/review expired/);assert.equal(f.sent.length,0);assert.equal(f.signCalls,0);}finally{Date.now=now;}});
