import {attachRecovery} from './recovery-app.mjs';
import {formatKas} from './models.mjs';
const root=document.querySelector('[data-contract-lab]'),q=s=>root.querySelector(s),esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),money=v=>formatKas(v).replace(' KAS',' tKAS');
const kind=root.dataset.contractKind||'refundable';
let token,busy=false,records=[],transactions=[],receiptTarget=null;
const say=message=>q('[data-contract-message]').textContent=message;
async function api(action,body={}){if(!token)token=(await(await fetch('/api/session')).json()).capability;const response=await fetch(`/api/testnet/${action}`,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Capability':token},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Testnet unavailable.');return data;}
async function run(action){if(busy)return;busy=true;root.setAttribute('aria-busy','true');q('[data-contract-picker]').disabled=true;try{await action();}catch(error){say(error.name==='TimeoutError'?'The operation timed out. Check the receipt before attempting another spend.':error.message);}finally{busy=false;root.removeAttribute('aria-busy');q('[data-contract-picker]').disabled=false;}}
function choose(){const id=q('[data-contract-picker]').value,contract=records.find(r=>r.id===id);const settlement=records.filter(r=>r.sourceContract===id).findLast(r=>transactions.some(t=>t.requestId===r.id));receiptTarget=settlement?.id||id;if(kind==='split'&&contract){q('[data-split-a]').textContent=contract.shareABps/100+'%';q('[data-split-b]').textContent=(100-contract.shareABps/100)+'%';}for(const button of root.querySelectorAll('[data-contract-action],[data-contract-check]'))button.disabled=!contract;q('[data-contract-terms]').innerHTML=contract?`<p><strong>1 tKAS</strong></p><p class="small">Contract rule: ${contract.kind==='split'?`${contract.shareABps/100}% to A; ${100-contract.shareABps/100}% to B. Split is fixed.`:esc(new Date(contract.refundAfter).toLocaleString())+'. The node determines eligibility.'}</p><details class="detail"><summary>Inspect compiled rules</summary><pre>${esc(JSON.stringify(contract.artifact,null,2))}</pre></details>`:'';q('[data-contract-result]').innerHTML='<p>Review a transaction to see the exact amount, fee, and destination before signing.</p>';q('[data-contract-receipt]').hidden=true;}
async function refresh(select){say('Checking Testnet-10…');const status=await api('status');records=status.requests;transactions=status.transactions;const picker=q('[data-contract-picker]'),previous=select||picker.value;picker.innerHTML='<option value="">Choose a contract</option>'+records.filter(r=>r.kind===kind).map(r=>`<option value="${esc(r.id)}">1 tKAS · ${esc(r.id.slice(0,8))}</option>`).join('');picker.value=records.some(r=>r.id===previous)?previous:records.filter(r=>r.kind===kind).at(-1)?.id||'';choose();q('[data-contract-create]').disabled=!status.connected;q('[data-contract-connect]').textContent='Refresh';say(status.connected?`Connected to Testnet-10. Test wallet: ${money(status.balance)}. Nothing happens without transaction review.`:status.error);}
q('[data-contract-connect]').addEventListener('click',()=>run(()=>refresh()));q('[data-contract-picker]').addEventListener('change',choose);
q('[data-contract-create]').addEventListener('click',()=>run(async()=>{const contract=await api(kind==='split'?'split':'contract',kind==='split'?{shareABps:Number(q('[data-split-ratio]').value)*100}:{});await refresh(contract.id);say('Compiled. The contract has not been funded. Review funding to lock 1 tKAS.');}));
for(const button of root.querySelectorAll('[data-contract-action]'))button.addEventListener('click',()=>run(async()=>{
  const id=q('[data-contract-picker]').value,entry=button.dataset.contractAction;const review=await api(entry==='fund'?'review':'contract-review',{requestId:id,entry});if(q('[data-contract-picker]').value!==id)return;
  receiptTarget=review.requestId||id;
  q('[data-contract-result]').innerHTML=`<h3>${entry==='fund'?'Fund the contract':entry==='claim'?'Recipient claim':entry==='distribute'?'Distribute to both recipients':'Sender refund'}</h3><dl class="record-fields">${[['Network',review.network],['Amount',money(review.amount)],['Fee',money(review.fee)],['Change',money(review.change)],['Destination',review.destination]].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>${review.outputs?.length>1?`<h3>Recipient payouts</h3>${review.outputs.map((output,index)=>`<p><strong>Recipient ${index===0?'A':'B'}: ${money(output.amount)}</strong><br><span class="record-id">${esc(output.address)}</span></p>`).join('')}`:''}<p class="small">Approval signs and submits this testnet transaction. Review expires after 60 seconds.</p><button class="primary-button" data-contract-approve>Approve this test transaction</button><details class="detail"><summary>Inspect transaction fields</summary><pre>${esc(JSON.stringify(review.transaction,null,2))}</pre></details>`;
  q('[data-contract-approve]').addEventListener('click',()=>run(async()=>{q('[data-contract-approve]').disabled=true;const result=await api('submit',{token:review.token});q('[data-contract-result]').innerHTML=`<h3>${result.state==='submitted'?'Submitted':'Submission uncertain'}</h3><p class="record-id">${esc(result.id)}</p><p>Check its receipt. A submission response does not establish acceptance.</p>`;say('Submission recorded. Check the transaction receipt.');}));say('Review ready. Nothing has been signed.');
}));
q('[data-contract-check]').addEventListener('click',()=>run(async()=>{const receipt=await api('receipt',{requestId:receiptTarget});const target=q('[data-contract-receipt]');target.hidden=false;target.innerHTML=`<h2>${esc(receipt.state)}</h2><dl class="record-fields">${[['Network',receipt.network],['Verified payment',money(receipt.verifiedAmount)],['Currently unspent',money(receipt.received)],['Transaction',receipt.transaction?.id||'None submitted'],['Accepting block',receipt.acceptingBlock||'Not verified'],['Checked',receipt.checked]].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><p>${esc(receipt.limitation)}</p>`;attachRecovery(target,receipt.transaction,{api,run,say});say(receipt.acceptingBlock?'Acceptance observed by the node.':'No acceptance is being claimed.');}));

if(kind==='split'){const ratio=q('[data-split-ratio]');ratio.addEventListener('input',()=>{q('[data-split-share]').textContent=ratio.value+'%';if(!q('[data-contract-picker]').value){q('[data-split-a]').textContent=ratio.value+'%';q('[data-split-b]').textContent=(100-Number(ratio.value))+'%';}});}
