export const contractsPage={file:'contracts.html',title:'Refundable transfer',description:'Compile, fund, claim, and refund a small experimental payment on Kaspa Testnet-10.',body:`
<div class="page-intro"><p class="eyebrow">Testnet Workshop · Silverscript</p><h1>A payment with a return path.</h1><p class="lead">The recipient can claim it. After the waiting period, the sender can also take it back. Try both paths with test coins.</p></div>
<aside class="testnet-notice"><strong>Testnet-10 only. Experimental, unaudited, never intended for mainnet.</strong><p>This local workshop controls both disposable test identities. Funds return to its test wallet. Nothing is automatically refunded, and the recipient’s permission does not expire.</p></aside>
<section class="workshop" data-contract-lab><div class="workshop-toolbar"><strong>Refundable transfer</strong><button class="quiet-button" data-contract-connect>Connect to Testnet-10</button></div><p class="workshop-message" data-contract-message role="status">Connect to prepare a new contract. Each contract holds 1 tKAS.</p><div class="contract-body"><div><div class="contract-paths"><article><span>Recipient</span><strong>Claim</strong><p>Recipient signature</p></article><div aria-hidden="true">or</div><article><span>Sender</span><strong>Refund</strong><p>Sender signature + elapsed time</p></article></div><div class="contract-result" data-contract-result><p>The spending rules are compiled into the locking script. A timer in this page cannot change them.</p></div></div><aside class="contract-controls"><button class="primary-button" data-contract-create disabled>Create a 1 tKAS contract</button><label class="select-control"><span>Your contracts</span><select data-contract-picker><option value="">Choose a contract</option></select></label><div data-contract-terms></div><div class="contract-buttons"><button class="quiet-button" data-contract-action="fund" disabled>Review funding</button><button class="quiet-button" data-contract-action="claim" disabled>Review recipient claim</button><button class="quiet-button" data-contract-action="refund" disabled>Review sender refund</button><button class="quiet-button" data-contract-check disabled>Check transaction receipt</button></div></aside></div><div class="receipt-surface" data-contract-receipt hidden></div></section>
<section class="chapter"><div class="section-title"><h2>Two ways to spend one output.</h2></div><p>The contract accepts a recipient signature at any time. Once the node’s time condition permits a refund, it can also accept the sender’s signature. Whichever valid spend is accepted first consumes the output. The other cannot spend it again.</p><p>Creation sets the refund threshold two minutes ahead of the node’s reported median time. Compiling does not fund the contract. Funding does not prove either spending path works.</p></section>
<details class="detail"><summary>Read the complete contract</summary><div class="detail-body"><pre class="source-code">contract RefundableTransfer(pubkey sender, pubkey recipient, temporal refundAfter) {
    entry claim(sig recipientSignature) {
        require(checkSig(recipientSignature, recipient));
    }
    entry refund(sig senderSignature) {
        require(checkSig(senderSignature, sender));
        require(tx.time >= refundAfter);
    }
}</pre><p><a href="/assets/refundable-transfer.sil">Download the source</a>. Adapted from <a href="https://github.com/kaspanet/silverscript/blob/v1-rc1/silverscript-lang/tests/examples/transfer_with_timeout.sil">Silverscript’s TransferWithTimeout example</a>, with CashScript attribution retained. The compiler is the pinned v1-rc1 prerelease.</p><p>This is a signature-and-time contract, not a guarantee of fair escrow or a recurring covenant. The two branches do not require cooperation. Recipient spending remains valid after refund eligibility begins.</p></div></details><p class="source-line"><a href="/testnet">Payment requests and receipts ↗</a> · <a href="/build-on-kaspa">More building blocks ↗</a></p><script type="module" src="/assets/contracts-app.mjs"></script>`};
