import {redemption,collateral,settlement} from './money-models.mjs';
const root=document.querySelector('[data-money]'),q=selector=>root.querySelector(selector),set=(selector,value)=>q(selector).textContent=value;
const dollars=cents=>`$${(cents/100).toFixed(2)}`;
const fragments={reserves:'redemption',collateral:'collateral',outcome:'prediction'};
function showView(view){
  for(const button of root.querySelectorAll('[data-money-view]'))button.setAttribute('aria-pressed',String(button.dataset.moneyView===view));
  for(const panel of root.querySelectorAll('[data-money-panel]'))panel.hidden=panel.dataset.moneyPanel!==view;
}
function restoreView(){showView(Object.keys(fragments).find(view=>fragments[view]===location.hash.slice(1))||'reserves');}
for(const button of root.querySelectorAll('[data-money-view]'))button.addEventListener('click',()=>{
  const view=button.dataset.moneyView;
  if(location.hash!==`#${fragments[view]}`)history.pushState(null,'',`#${fragments[view]}`);
  showView(view);
});
window.addEventListener('hashchange',restoreView);
window.addEventListener('popstate',restoreView);
restoreView();
function renderRedemption(){const s=redemption(Number(q('[data-redemption]').value)*100);set('[data-requested]',s.requested/100);set('[data-paid]',dollars(s.paid));set('[data-pending]',`${s.pending/100} tokens still waiting`);set('[data-reserves]',dollars(s.reserves));set('[data-cash]',`${dollars(s.cash)} cash · $80.00 Treasuries`);set('[data-outstanding]',s.outstanding/100);q('[data-cash-bar]').style.width=`${100*s.cash/s.reserves}%`;q('[data-treasury-bar]').style.width=`${100*s.treasuries/s.reserves}%`;set('[data-redemption-answer]',s.pending?`The issuer can pay ${dollars(s.paid)} now. The remaining ${s.pending/100} tokens wait for cash, even though modeled assets still cover every token.`:`The ${s.requested/100} requested tokens can be redeemed from available cash. Only those paid tokens are burned.`);}
function renderCollateral(){const s=collateral(Number(q('[data-collateral-price]').value));set('[data-price]',dollars(s.price));q('[data-collateral-price]').setAttribute('aria-valuetext',`${dollars(s.price)} per coin`);set('[data-collateral-value]',dollars(s.value));set('[data-health]',s.health.toFixed(3));q('[data-health-position]').style.left=`${Math.min(100,100*s.health/3)}%`;q('[data-health-position]').closest('.collateral-scale').setAttribute('aria-label',`Health factor ${s.health.toFixed(3)}. Liquidation becomes eligible below one.`);set('[data-collateral-verdict]',s.eligible?'Liquidation eligible':'Above the liquidation threshold');set('[data-collateral-answer]',s.eligible?'The modeled rule now permits liquidation. Nothing has been sold by this illustration.':'The collateral supports the debt under this example’s rule. That is not a guarantee against future losses.');}
function renderOutcome(){const s=settlement(q('[data-outcome]').value);q('[data-money-panel=outcome]').dataset.resolution=s.outcome;set('[data-yes]',dollars(s.yes));set('[data-no]',dollars(s.no));set('[data-locked]',dollars(s.locked));set('[data-outcome-verdict]',s.outcome==='pending'?'Waiting for a result':`${s.outcome==='yes'?'Yes':'No'} claims receive the pool`);set('[data-outcome-answer]',s.outcome==='pending'?'The $100 stays locked. Neither side can redeem an outcome payout yet.':'The winning claims receive $100 in total. The losing claims receive $0. Creating two sides did not create a second $100.');}
q('[data-redemption]').addEventListener('input',renderRedemption);q('[data-collateral-price]').addEventListener('input',renderCollateral);q('[data-outcome]').addEventListener('change',renderOutcome);renderRedemption();renderCollateral();renderOutcome();

const walkthrough=document.createElement('div');walkthrough.className='model-walkthrough';
walkthrough.innerHTML='<div><p class="eyebrow" data-money-progress>Try this example</p><h3 data-money-guide-title>Can every token be redeemed immediately?</h3><p data-money-guide-explanation aria-live="polite">Follow the money through three different promises. Each step changes the model below.</p></div><div class="walkthrough-actions"><button class="primary-button" data-money-continue>Start the example</button><button class="quiet-button" data-money-restart hidden>Start again</button></div>';
root.prepend(walkthrough);
const tour=[['reserves','[data-redemption]',20,'Redeem the available cash','The issuer has $20 cash. A request for 20 tokens can be paid immediately.'],['reserves','[data-redemption]',40,'Ask for more than the cash available','The remaining assets still have value in this model, but they are not cash available for immediate redemption.'],['collateral','[data-collateral-price]',1000,'Borrow against valuable collateral','The collateral supports the loan at this example price.'],['collateral','[data-collateral-price]',500,'Let the price fall','The debt does not fall with the collateral price. Crossing the threshold makes liquidation eligible; someone must still execute it.'],['outcome','[data-outcome]','pending','Wait for the reported result','One pool backs both possible outcomes. Pending claims do not each receive half.'],['outcome','[data-outcome]','yes','Report Yes','The Yes side receives the pool. The example’s authority supplies that answer; the blockchain does not discover it.']];
let tourIndex=-1;const next=walkthrough.querySelector('[data-money-continue]'),again=walkthrough.querySelector('[data-money-restart]');
function advanceTour(){tourIndex++;const [view,selector,value,title,explanation]=tour[tourIndex];root.querySelector(`[data-money-view="${view}"]`).click();const input=root.querySelector(selector);input.value=String(value);input.dispatchEvent(new Event(input.tagName==='SELECT'?'change':'input',{bubbles:true}));walkthrough.querySelector('[data-money-progress]').textContent=`Step ${tourIndex+1} of ${tour.length}`;walkthrough.querySelector('[data-money-guide-title]').textContent=title;walkthrough.querySelector('[data-money-guide-explanation]').textContent=explanation;next.disabled=tourIndex===tour.length-1;next.textContent=next.disabled?'Example complete':'Continue';again.hidden=false;if(matchMedia('(max-width:700px)').matches)walkthrough.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}
next.addEventListener('click',advanceTour);again.addEventListener('click',()=>{tourIndex=-1;next.disabled=false;advanceTour();next.focus();});

root.dataset.guided='true';const explore=document.createElement('button');explore.className='quiet-button walkthrough-explore';explore.textContent='Explore controls';explore.setAttribute('aria-expanded','false');walkthrough.append(explore);explore.addEventListener('click',()=>{const expanded=root.dataset.guided==='true';root.dataset.guided=String(!expanded);explore.setAttribute('aria-expanded',String(expanded));explore.textContent=expanded?'Hide controls':'Explore controls';});
