// The same calculated snapshot renders on the server and in the browser.
export function networkDiagram(s,{interactive=false,selected=null,id='network'}={}){
  const visible=[true,s.foundB,s.foundC,s.time>=1200];
  const heading=!s.foundB?'Both miners know the earlier block':!s.foundC?'One miner finds a new block':s.parallel?'Two miners. Two independent blocks.':'The next miner builds on that block.';
  const explanation=!s.foundB?'Each miner can start looking for the next block.':!s.foundC?(s.time>=s.receivedB?'The news reaches miner 2. It can build on B.':'The news is still traveling. Miner 2 has not seen B yet.'):s.parallel?'Miner 2 found C before hearing about B. Both blocks build on A.':'Miner 2 heard about B in time. Its block C builds on B.';
  const names=['A','B','C','D'];
  const labels=['Earlier block','Miner 1 · 100 ms','Miner 2 · 400 ms','Possible later block'];
  const relations=['Known to both','References A',`References ${s.parent}`,s.parallel?'To B + C':'References C'];
  const paths=s.parallel?[[1,0],[2,0],[3,1],[3,2]]:[[1,0],[2,1],[3,2]];
  const svg=compact=>{
    const points=compact?(s.parallel?[[55,210],[180,95],[180,325],[305,210]]:[[55,60],[135,160],[215,260],[305,360]]):(s.parallel?[[80,150],[285,70],[285,230],[590,150]]:[[75,150],[265,150],[455,150],[645,150]]);
    const half=compact?48:70,marker=`${id}-${compact?'small':'wide'}`;
    return `<svg class="network-drawing ${compact?'drawing-small':'drawing-wide'}" viewBox="0 0 ${compact?'360 450':'720 310'}" role="group" aria-label="${s.parallel?'Parallel block references':'Sequential block references'}"><defs><marker id="${marker}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L10 5 L0 10" fill="none" stroke="currentColor" stroke-width="1.5"/></marker></defs>${paths.filter(([from,to])=>visible[from]&&visible[to]).map(([from,to])=>`<path class="block-reference" d="M${points[from][0]-half-2} ${points[from][1]} L${points[to][0]+half+5} ${points[to][1]}" marker-end="url(#${marker})"/>`).join('')}${points.map(([x,y],i)=>visible[i]?`<g class="diagram-block" data-block="${names[i]}" ${interactive?`role="button" tabindex="0" aria-pressed="${selected===names[i]}"`: 'role="img"'} aria-label="Block ${names[i]}. ${labels[i]}. ${relations[i]}" transform="translate(${x} ${y})"><rect class="block-depth" x="${-half+6}" y="-23" width="${half*2}" height="58" rx="12"/><path class="block-top" d="M${-half+10} -31 L${-half+16} -39 H${half-4} Q${half+6} -39 ${half+6} -29 L${half} -21 Z"/><rect class="block-face" x="${-half}" y="-31" width="${half*2}" height="58" rx="13"/><text class="block-name" y="-5" text-anchor="middle">Block ${names[i]}</text><text class="block-relation" y="13" text-anchor="middle">${compact?(["Both miners","To A",`To ${s.parent}`,s.parallel?"To B + C":"To C"][i]):relations[i]}</text><text class="block-owner" y="53" text-anchor="middle">${compact?['<tspan x="0">Earlier</tspan><tspan x="0" dy="20">block</tspan>','<tspan x="0">Miner 1</tspan><tspan x="0" dy="20">100 ms</tspan>','<tspan x="0">Miner 2</tspan><tspan x="0" dy="20">400 ms</tspan>','<tspan x="0">Possible</tspan><tspan x="0" dy="20">later block</tspan>'][i]:i===3?'<tspan x="0">Possible later</tspan><tspan x="0" dy="20">block</tspan>':labels[i]}</text></g>`:'').join('')}</svg>`;
  };
  return `<div class="diagram-caption"><strong>${heading}</strong><p>${explanation}</p><small>Arrows reference earlier blocks.${s.time>=1200?' D shows how a later block can connect the history.':''}</small></div>${svg(false)}${svg(true)}`;
}
