import {createPublicAssetsUI,validatePublicAssetsState} from './public-assets-ui.mjs';
import {observePublicAcceptance} from './public-acceptance.mjs';
import {derivePublicRecoveryPlan} from './public-recovery.mjs';
import {PUBLIC_NETWORK,instantiatePublicContract,buildPublicFunding,buildPublicSpend,signPublicPlan,preflightPublicContract,validatePublicPlan} from './public-contracts.mjs';
const root=document.querySelector('[data-public-apps]');
const q=name=>root.querySelector(`[data-public-${name}]`),set=(name,value)=>{q(name).textContent=value;};
const kinds={
 escrow:{title:'Pay when the work is done.',description:'The buyer releases the coins to the seller. An arbiter can resolve a disagreement. After two minutes of node time, the buyer can request a refund.',amount:20000000,maxFee:1000000,objects:['Buyer','Contract','Seller'],actions:[['release','Release to seller',{}],['resolve','Arbiter: pay seller',{paySeller:true}],['resolve','Arbiter: refund buyer',{paySeller:false}],['refund','Buyer: timed refund',{}]]},
 treasury:{title:'Two signatures open the treasury.',description:'Any two of three members can approve a withdrawal. This example owns all three role keys, so you can try each allowed pair.',amount:20000000,maxFee:1000000,objects:['3 members','2 signatures','Payout'],actions:[['spend','Members A + B',{pair:0}],['spend','Members A + C',{pair:1}],['spend','Members B + C',{pair:2}]]},
 prediction:{title:'One pool. A stated outcome.',description:'After one minute, the oracle chooses Yes or No and pays that side. After two minutes, either participant can request an equal refund. The oracle supplies the answer; the contract does not establish its truth.',amount:20000000,maxFee:1000000,objects:['Yes','One pool','No'],actions:[['settle','Oracle: Yes wins',{yesWins:true}],['settle','Oracle: No wins',{yesWins:false}],['refund','Refund both sides',{refundBy:'yes'}]]},
 proof:{title:'A valid proof unlocks the payout.',description:'Verify the published Groth16 example proof and return the remaining coins to this wallet. This uses an existing proof fixture, not newly generated private evidence.',amount:50000000,maxFee:20000000,objects:['Proof','Verify','Payout'],actions:[['verify','Verify proof and pay',{}]]}
};
let sdk,rpc,templates,keys=[],password='',session=null,contract=null,kind='escrow',plan=null,busy=false,exported=false,activeAccount=0,accountBalances=[0n,0n,0n];
const STORE='kaspa-public-encrypted-recovery-v1';
const kas=value=>`${(Number(value)/1e8).toLocaleString('en-US',{maximumFractionDigits:8})} tKAS`;
const message=(value,error=false)=>{set('message',value);q('message').dataset.error=String(error);};
const timeout=(promise,ms=12000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>{const error=new Error('Node timeout');error.safeMessage='The node did not respond. Check again before taking another action.';reject(error);},ms))]);
async function action(fn){if(busy)return;busy=true;root.setAttribute('aria-busy','true');try{await fn();}catch(error){message(error?.safeMessage||'This action could not complete. Check the network, balance, recovery password, and contract timing, then try again. No automatic retry was sent.',true);}finally{busy=false;root.removeAttribute('aria-busy');}}
function fail(text){const error=new Error(text);error.safeMessage=text;throw error;}
async function initialize(){if(!sdk){sdk=await import('/assets/kaspa/kaspa.js');await sdk.default({module_or_path:'/assets/kaspa/kaspa_bg.wasm'});const response=await fetch('/assets/public-templates.json');if(!response.ok)fail('Contract templates are unavailable.');templates=await response.json();if(templates.version!==1||templates.network!==PUBLIC_NETWORK)fail('The installed templates are not for this Testnet-10 application.');}if(!rpc){for(const options of [{resolver:new sdk.Resolver(),networkId:PUBLIC_NETWORK},{url:'wss://muon-10.kaspa.blue/kaspa/testnet-10/wrpc/borsh',networkId:PUBLIC_NETWORK}]){const candidate=new sdk.RpcClient(options);try{await timeout(candidate.connect({blockAsyncConnect:true,timeoutDuration:6000}),8000);rpc=candidate;break;}catch{try{await candidate.disconnect();}catch{}}}if(!rpc)fail('A Testnet-10 connection could not be established. Try restoring or connecting again.');}await nodeInfo();}
async function nodeInfo(){const info=await timeout(rpc.getServerInfo());if(info.networkId!==PUBLIC_NETWORK||info.isSynced!==true||info.hasUtxoIndex!==true)fail('Sending is blocked: a synchronized Testnet-10 node with a UTXO index is required.');const dag=await timeout(rpc.getBlockDagInfo()),estimate=await timeout(rpc.getFeeEstimate()),feeRate=Math.max(100,Math.ceil(estimate.estimate.priorityBucket.feerate));if(!Number.isFinite(feeRate)||feeRate>100000)fail('The node returned an unusable fee estimate.');set('connection','Connected to Testnet-10');return {...info,pastMedianTime:dag.pastMedianTime,feeRate};}
function newKey(){for(let i=0;i<8;i++){const bytes=crypto.getRandomValues(new Uint8Array(32));try{return new sdk.PrivateKey(Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''));}catch{}}fail('Could not create a disposable key.');}
const owner=()=>keys[activeAccount].toPublicKey().toXOnlyPublicKey().toString();
const walletAddress=()=>keys[0].toAddress(PUBLIC_NETWORK).toString();
const fundingAddress=()=>keys[activeAccount].toAddress(PUBLIC_NETWORK).toString();
async function refresh(){await nodeInfo();const addresses=keys.map(key=>key.toAddress(PUBLIC_NETWORK).toString()),{entries}=await timeout(rpc.getUtxosByAddresses(addresses));for(let index=0;index<3;index++){const amount=entries.filter(e=>e.address?.toString()===addresses[index]||e.entry.scriptPublicKey.script===sdk.payToAddressScript(new sdk.Address(addresses[index])).script).reduce((sum,e)=>sum+BigInt(e.amount),0n);accountBalances[index]=amount;q('account-select').options[index].textContent=`${['Main','Second','Third'][index]} account · ${kas(amount)}`;}const selected=entries.filter(e=>e.entry.scriptPublicKey.script===sdk.payToAddressScript(new sdk.Address(fundingAddress())).script);set('balance',kas(selected.reduce((sum,e)=>sum+BigInt(e.amount),0n)));q('address').value=fundingAddress();q('account-select').disabled=Boolean(session?.journal&&!session.journal.observed)||assetsUI.pending();return selected;}

function showWallet(){q('start').hidden=true;q('wallet').hidden=false;q('address').value=fundingAddress();selectKind(kind);}
function selectKind(next){assetsUI.invalidate();q('assets').hidden=true;q('example').hidden=false;q('contract').hidden=!contract;for(const button of root.querySelectorAll('[data-public-asset-kind]'))button.setAttribute('aria-pressed','false');if(contract&&session?.contract&&!session?.completed&&next!==kind){message('Finish the current contract before choosing another application. Your recovery file preserves its keys.');return;}kind=next;q('contract').hidden=!contract||contract.kind!==kind;for(const button of root.querySelectorAll('[data-public-kind]'))button.setAttribute('aria-pressed',String(button.dataset.publicKind===kind));const spec=kinds[kind];set('title',spec.title);set('description',spec.description);set('cost',kind==='proof'?'Deposit: 0.5 tKAS. Proof verification can cost about 0.18 tKAS or more; review the exact fee before funding.':'Deposit: 0.2 tKAS. Contract fee cap: 0.01 tKAS. Funding has a separate fee.');q('object').replaceChildren(...spec.objects.map((label,index)=>{const box=document.createElement('div');box.className='public-object-box';const small=document.createElement('span');small.textContent=label;const number=document.createElement('strong');number.textContent=index===1?kas(spec.amount):index===0?'①':'②';box.append(small,number);return box;}));}
function baseState(info){const [a,b,c]=keys.map(key=>key.toPublicKey().toXOnlyPublicKey().toString()),now=Number(info.pastMedianTime),base={principal:kinds[kind].amount,maxFee:kinds[kind].maxFee};if(!Number.isSafeInteger(now))fail('The node did not provide a usable median time.');if(kind==='escrow')return {...base,buyer:a,seller:b,arbiter:c,refundAfter:now+120000};if(kind==='treasury')return {...base,memberA:a,memberB:b,memberC:c};if(kind==='prediction')return {...base,yesOwner:a,noOwner:b,oracle:c,resolveAfter:now+60000,refundAfter:now+120000};return {...base,owner:a};}
function showContract(){q('contract').hidden=false;q('contract-address').value=contract.address;set('principal',kas(contract.state.principal));q('actions').hidden=true;q('fund').disabled=!exported;q('backup-confirm').checked=false;q('action-options').replaceChildren(...kinds[kind].actions.map(([entry,label,parameters])=>{const button=document.createElement('button');button.textContent=label;button.addEventListener('click',()=>action(()=>reviewSpend(entry,parameters,label)));return button;}));}
const encode=bytes=>{let result='';for(let index=0;index<bytes.length;index+=32768)result+=String.fromCharCode(...bytes.subarray(index,index+32768));return btoa(result);},decode=text=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
async function encryptionKey(secret,salt){const raw=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encryptRecovery(){if(password.length<12)fail('Use a recovery password of at least 12 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await encryptionKey(password,salt);const payload={version:1,network:PUBLIC_NETWORK,keys:keys.map(key=>key.toString()),walletAddress:walletAddress(),session};const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return {version:1,network:PUBLIC_NETWORK,kdf:'PBKDF2-SHA256',iterations:250000,salt:encode(salt),iv:encode(iv),ciphertext:encode(new Uint8Array(ciphertext))};}
async function persist(){const encrypted=await encryptRecovery();try{localStorage.setItem(STORE,JSON.stringify(encrypted));if(!localStorage.getItem(STORE))throw new Error();}catch{fail('Encrypted recovery could not be saved in this browser. New submissions are blocked. Enable browser storage or use another browser.');}return encrypted;}
function download(value){const blob=new Blob([JSON.stringify(value)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kaspa-testnet-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function strictFields(value,names){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(key=>names.includes(key));}
function transactionOutputs(tx){return tx.outputs.map((out,index)=>({index,amount:String(out.value),address:sdk.addressFromScriptPublicKey(out.scriptPublicKey,PUBLIC_NETWORK).toString(),script:out.scriptPublicKey.script}));}
function recoveredSession(value,restored){
 if(!strictFields(value,['contract','completed','journal','assets'])||typeof value.completed!=='boolean')fail('Invalid recovered session.');
 if(value.contract===null){if(value.journal)fail('A transaction journal requires its contract.');value.assets=validatePublicAssetsState(sdk,templates.templates,value.assets,restored.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()));return {rebuilt:null,value};}
 value.assets=validatePublicAssetsState(sdk,templates.templates,value.assets,restored.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()));
 const saved=value.contract;
 if(!strictFields(saved,['kind','state','script','address','templateVersion'])||!kinds[saved.kind]||saved.templateVersion!==1)fail('Invalid recovered contract.');
 const rebuilt=instantiatePublicContract(sdk,templates.templates[saved.kind],saved.state);
 if(rebuilt.script!==saved.script||rebuilt.address!==saved.address)fail('Recovered contract differs from the installed template.');
 const publicKeys=restored.map(k=>k.toPublicKey().toXOnlyPublicKey().toString());
 const roles=Object.entries(saved.state).filter(([name])=>!['principal','maxFee','refundAfter','resolveAfter'].includes(name));
 if(roles.some(([,key])=>!publicKeys.includes(key)))fail('A recovered role does not match this wallet’s keys.');
 if(value.journal){
  const j=value.journal;
  if(!strictFields(j,['id','transaction','funding','observed','submitted','outputs','attempted','checkpoint','scanCursor','acceptingBlock','scanCaughtUp','outputsObserved'])||typeof j.transaction!=='string'||j.transaction.length>750000||typeof j.funding!=='boolean'||typeof j.observed!=='boolean'||typeof j.submitted!=='boolean'||(j.attempted!==undefined&&typeof j.attempted!=='boolean'))fail('Invalid recovered transaction journal.');
  const recovered=derivePublicRecoveryPlan(sdk,{contract:rebuilt,journal:j,keysPublic:publicKeys});
  const outputs=transactionOutputs(recovered.transaction);
  j.outputs=outputs;j.observed=false;j.outputsObserved=false;if(j.checkpoint&&!/^[a-f0-9]{64}$/.test(j.checkpoint))fail('Invalid receipt checkpoint.');j.scanCursor=j.checkpoint||null;j.acceptingBlock=null;j.scanCaughtUp=false;
 }
 value.completed=false;return {rebuilt,value};
}
async function restore(fromLocal=false){
 let envelope;if(fromLocal){const saved=localStorage.getItem(STORE);if(!saved||saved.length>4000000)fail('No valid encrypted recovery is saved in this browser.');envelope=JSON.parse(saved);}else{const file=q('import-file').files[0];if(!file||file.size>4000000)fail('Choose a recovery JSON file smaller than 4 MB.');envelope=JSON.parse(await file.text());}
 if(!strictFields(envelope,['version','network','kdf','iterations','salt','iv','ciphertext'])||envelope.version!==1||envelope.network!==PUBLIC_NETWORK||envelope.kdf!=='PBKDF2-SHA256'||envelope.iterations!==250000)fail('This is not a supported Testnet-10 recovery file.');
 const salt=decode(envelope.salt),iv=decode(envelope.iv);if(salt.length!==16||iv.length!==12)fail('Invalid recovery file.');
 const secret=q('import-password').value,key=await encryptionKey(secret,salt),clear=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,decode(envelope.ciphertext));
 const value=JSON.parse(new TextDecoder().decode(clear));
 if(!strictFields(value,['version','network','keys','walletAddress','session'])||value.version!==1||value.network!==PUBLIC_NETWORK||!Array.isArray(value.keys)||value.keys.length!==3||value.keys.some(k=>typeof k!=='string'||!/^[a-f0-9]{64}$/i.test(k)))fail('The decrypted recovery data is invalid.');
 try{await initialize();}catch(error){rpc=null;throw error;}const restored=value.keys.map(k=>new sdk.PrivateKey(k));
 if(restored[0].toAddress(PUBLIC_NETWORK).toString()!==value.walletAddress)fail('The recovery address does not match its key.');
 const checked=recoveredSession(value.session,restored);
 keys=restored;password=secret;session=checked.value;contract=checked.rebuilt;if(contract)kind=contract.kind;exported=true;q('import-password').value='';
 showWallet();if(contract)showContract();q('backup').hidden=true;await refresh();if(contract)await checkContract();if(session.journal)showReceipt();
 message('Recovery decrypted and addresses checked. The node will determine which outputs remain spendable.');
}

async function prepare(){if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(session?.journal&&!session.journal.observed)fail('Check the previous transaction before preparing another contract.');if(contract&&!session?.completed)fail('Finish the current contract first.');const info=await nodeInfo();contract=instantiatePublicContract(sdk,templates.templates[kind],baseState(info));const preflight=preflightPublicContract(sdk,contract,{feeRate:info.feeRate});session={assets:session?.assets,contract:{kind,state:contract.state,script:contract.script,address:contract.address,templateVersion:1},completed:false};set('exit-cost',`Exit preflight: ${preflight.exits.map(exit=>`${exit.entry} ${kas(exit.fee)}`).join(' · ')}. These are calculated fees; review the transaction before sending.`);exported=exported&&password.length>=12;showContract();q('backup').hidden=exported;set('step','2 · Contract prepared → Save recovery → Review funding → Verify');message('Contract prepared. Save its recovery file before locking test coins.');}
async function checkContract(){await nodeInfo();const {entries}=await timeout(rpc.getUtxosByAddresses([contract.address]));const exact=entries.filter(e=>BigInt(e.amount)===BigInt(contract.state.principal)&&e.entry.scriptPublicKey.script===sdk.payToScriptHashScript(contract.script).script);q('actions').hidden=exact.length!==1;q('fund').disabled=!exported||exact.length>0||Boolean(session?.journal&&!session.journal.observed);set('contract-status',exact.length===1?'The node currently reports the exact contract output as unspent. Choose an action below.':exact.length>1?'More than one matching output exists. New actions are blocked to avoid choosing the wrong deposit.':'No exact unspent contract output is visible at this node.');return exact;}
function showReview(purpose){q('review').hidden=false;set('review-purpose',purpose);const total=plan.transaction.inputs.reduce((sum,input)=>sum+BigInt(input.utxo.amount),0n);const items=[['Network',PUBLIC_NETWORK],['Fee',kas(plan.fee)],['Total input',kas(total)],...plan.transaction.outputs.map((out,index)=>[`Output ${index+1} · ${kas(out.value)}`,sdk.addressFromScriptPublicKey(out.scriptPublicKey,PUBLIC_NETWORK)?.toString()||'Contract output'])];q('review-details').replaceChildren(...items.flatMap(([label,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;return [dt,dd];}));q('submit').disabled=false;q('submit').textContent='Sign and save transaction recovery';q('review').focus();}
async function reviewFunding(){if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(!exported)fail('Save and acknowledge your recovery file first.');if(session?.journal&&!session.journal.observed)fail('Check the pending transaction first.');const entries=await refresh();if((await checkContract()).length)fail('This contract is already funded.');const info=await nodeInfo();plan=buildPublicFunding(sdk,{contract,fundingUtxos:entries.slice(0,8),owner:owner(),feeRate:info.feeRate});plan.reviewedAt=Date.now();showReview(`Lock ${kas(contract.state.principal)} in this ${kind} contract. Change returns to your test wallet.`);}
async function reviewSpend(entry,parameters,label){if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(session?.journal&&!session.journal.observed)fail('Check the pending transaction first.');const info=await nodeInfo(),entries=await checkContract();if(entries.length!==1)fail('Exactly one matching unspent contract output is required.');plan=buildPublicSpend(sdk,{contract,utxo:entries[0],entry,parameters,pastMedianTime:info.pastMedianTime,feeRate:info.feeRate});plan.reviewedAt=Date.now();showReview(label);}
function showReceipt(){q('receipt').hidden=false;const j=session.journal;set('receipt-state',j.acceptingBlock?`This node includes the transaction in accepted-chain history (block ${j.acceptingBlock.slice(0,12)}…).`:j.observed?'The node currently reports this transaction’s exact outputs as unspent.':j.submitted?'The node returned the expected transaction ID. Output observation is still pending.':'Submission is uncertain or has not yet been attempted. Check the node before taking another action.');const link=q('transaction-link');link.textContent=j.id;link.href=`https://tn10.kaspa.stream/transactions/${j.id}`;}
async function submit(){
 if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(!plan)fail('Review a transaction first.');const current=await nodeInfo();
 if(current.feeRate>plan.mass.feeRate)fail('The current fee estimate increased. Cancel and review again before signing, or wait before resubmitting the saved transaction.');
 if(!plan.signed){
  if(Date.now()-plan.reviewedAt>60000)fail('The review expired. Cancel and review the current outputs again.');const {sink}=await timeout(rpc.getSink());
  await signPublicPlan(plan,(tx,index,{publicKey})=>{const key=keys.find(k=>k.toPublicKey().toXOnlyPublicKey().toString()===publicKey);if(!key)fail('The required role key is not in this wallet.');return sdk.createInputSignature(tx,index,key);});
  session.journal={checkpoint:sink,id:plan.transaction.id,transaction:plan.transaction.serializeToSafeJSON(),funding:Boolean(plan.funding),observed:false,submitted:false,outputs:transactionOutputs(plan.transaction)};plan.signed=true;
 }
 if(!plan.recoverySaved&&!plan.recovery){download(await persist());plan.recoverySaved=true;showReceipt();q('submit').textContent='I saved recovery · submit transaction';message('The signed transaction has been encrypted and saved. Save the downloaded recovery file, then submit.');return;}
 if(session.journal.attempted&&!plan.recovery)fail('This transaction was already attempted. Check its node observation; it will not be submitted again automatically.');validatePublicPlan(plan);session.journal.attempted=true;await persist();q('submit').disabled=true;
 try{const result=await timeout(rpc.submitTransaction({transaction:plan.transaction,allowOrphan:false}));if(result.transactionId!==session.journal.id)fail('The node returned a different transaction ID. Treat this submission as uncertain.');session.journal.submitted=true;await persist();message('Submitted to Testnet-10. Check what the node now observes.');}finally{q('review').hidden=true;showReceipt();plan=null;}await checkReceipt();
}
async function checkReceipt(){await nodeInfo();const j=session?.journal;if(!j)fail('No recorded transaction.');const {entries}=await timeout(rpc.getUtxosByAddresses([...new Set(j.outputs.map(out=>out.address))]));j.outputsObserved=j.outputs.every(out=>entries.some(e=>e.outpoint.transactionId===j.id&&e.outpoint.index===out.index&&String(e.amount)===out.amount&&e.entry.scriptPublicKey.version===0&&e.entry.scriptPublicKey.script===out.script&&!e.entry.covenantId));if(j.checkpoint)Object.assign(j,await observePublicAcceptance(rpc,j,{call:timeout}));j.observed=Boolean(j.acceptingBlock)||j.outputsObserved;session.completed=j.observed&&!j.funding;await persist();showReceipt();await refresh();await checkContract();message(j.acceptingBlock?'Transaction found in this node’s accepted-chain history. This is a current observation, not a finality guarantee.':j.observed?'Matching transaction outputs observed at this node. This is a current UTXO observation, not a finality guarantee.':'Matching outputs are not yet visible. The transaction remains pending or uncertain; new spends stay blocked.');}
q('create').addEventListener('click',()=>action(async()=>{await initialize();keys=[newKey(),newKey(),newKey()];session={contract:null,completed:true};showWallet();await refresh();message('Disposable test wallet created. Save its recovery file, then receive test coins and prepare an application.');}));
q('import').addEventListener('click',()=>action(()=>restore(false)));q('import-local').addEventListener('click',()=>action(()=>restore(true)));q('refresh').addEventListener('click',()=>action(refresh));for(const button of root.querySelectorAll('[data-public-kind]'))button.addEventListener('click',()=>selectKind(button.dataset.publicKind));q('prepare').addEventListener('click',()=>action(prepare));
q('export').addEventListener('click',()=>action(async()=>{password=q('backup-password').value||password;download(await persist());q('backup-password').value='';q('backup-confirm').disabled=false;message('Encrypted recovery downloaded. Confirm that you saved it before funding.');}));q('backup-confirm').addEventListener('change',()=>action(async()=>{exported=q('backup-confirm').checked;set('step',exported?'3 · Recovery saved → Review funding → Verify':'2 · Save recovery → Review funding → Verify');if(contract)await checkContract();if(exported)q('backup').hidden=true;}));q('fund').addEventListener('click',()=>action(reviewFunding));q('check').addEventListener('click',()=>action(checkContract));q('submit').addEventListener('click',()=>action(submit));q('cancel').addEventListener('click',()=>{plan=null;q('review').hidden=true;});q('check-receipt').addEventListener('click',()=>action(checkReceipt));
window.addEventListener('beforeunload',event=>{if(keys.length&&session&&!session.completed){event.preventDefault();event.returnValue='';}});

q('resume').addEventListener('click',()=>action(async()=>{const j=session?.journal;if(!j||j.observed)fail('No unresolved transaction needs recovery.');await nodeInfo();plan=derivePublicRecoveryPlan(sdk,{contract,journal:j,keysPublic:keys.map(key=>key.toPublicKey().toXOnlyPublicKey().toString())});showReview('Resubmit the identical saved transaction. Its ID, inputs, outputs, and fee remain unchanged.');q('submit').textContent='Submit the identical saved transaction';}));

q('account-select').addEventListener('change',()=>action(async()=>{if((session?.journal&&!session.journal.observed)||assetsUI.pending())fail('Check the unresolved transaction before changing accounts.');assetsUI.invalidate();activeAccount=Number(q('account-select').value);plan=null;q('review').hidden=true;await refresh();}));
q('copy-address').addEventListener('click',()=>action(async()=>{await navigator.clipboard.writeText(fundingAddress());message('Receive address copied. Use Testnet-10 coins only.');}));

q('show-backup').addEventListener('click',()=>{q('backup').hidden=false;q('backup-password').focus();});

const assetsUI=createPublicAssetsUI(q('assets'),{
 context:()=>({sdk,templates:templates?.templates,rpc,owners:keys.map(key=>key.toPublicKey().toXOnlyPublicKey().toString()),addresses:keys.map(key=>key.toAddress(PUBLIC_NETWORK).toString()),account:activeAccount,balances:accountBalances,call:timeout}),
 action,message,fail,nodeInfo,refresh,
 getState:()=>session?.assets,
 saveState:async value=>{if(!session)fail('Create or restore a wallet first.');session.assets=value;await persist();},
 encrypted:persist,download,hasRecovery:()=>exported&&password.length>=12,pending:()=>Boolean(session?.journal&&!session.journal.observed),
 sign:(tx,index,{owner:publicKey})=>{const key=keys.find(key=>key.toPublicKey().toXOnlyPublicKey().toString()===publicKey);if(!key)fail('Required signing account is missing.');return sdk.createInputSignature(tx,index,key);}
});
function openAssets(kind){q('example').hidden=true;q('contract').hidden=true;q('review').hidden=true;plan=null;for(const button of root.querySelectorAll('[data-public-kind]'))button.setAttribute('aria-pressed','false');for(const button of root.querySelectorAll('[data-public-asset-kind]'))button.setAttribute('aria-pressed',String(button.dataset.publicAssetKind===kind));assetsUI.open(kind);}
for(const button of root.querySelectorAll('[data-public-asset-kind]'))button.addEventListener('click',()=>openAssets(button.dataset.publicAssetKind));
q('send').addEventListener('click',()=>openAssets('payment'));
