import {createPublicAssetsUI,validatePublicAssetsState} from './public-assets-ui.mjs';
import {observePublicAcceptance} from './public-acceptance.mjs';
import {derivePublicRecoveryPlan} from './public-recovery.mjs';
import {PUBLIC_NETWORK,instantiatePublicContract,buildPublicFunding,buildPublicSpend,signPublicPlan,preflightPublicContract,validatePublicPlan} from './public-contracts.mjs';
const root=document.querySelector('[data-public-apps]');
const q=name=>root.querySelector(`[data-public-${name}]`),set=(name,value)=>{q(name).textContent=value;};
const kinds={
 escrow:{title:'Pay when the work is done.',description:'The buyer releases the coins to the seller. An arbiter can resolve a disagreement. After two minutes of node time, the buyer can request a refund.',amount:20000000,maxFee:1000000,objects:['Buyer','Contract','Seller'],actions:[['release','Release to seller',{}],['resolve','Arbiter: pay seller',{paySeller:true}],['resolve','Arbiter: refund buyer',{paySeller:false}],['refund','Buyer: timed refund',{}]]},
 treasury:{title:'Two signatures open the treasury.',description:'Any two of three members can approve a withdrawal. This example owns all three role keys, so you can try each allowed pair.',amount:20000000,maxFee:1000000,objects:['3 members','2 signatures','Payout'],actions:[['spend','Members A + B',{pair:0}],['spend','Members A + C',{pair:1}],['spend','Members B + C',{pair:2}]]},
 prediction:{title:'One pool. A stated outcome.',description:'After 15 seconds, the oracle can choose Yes or No and pay that side. After one minute, either participant can request an equal refund. The oracle supplies the answer; the contract does not establish its truth.',amount:20000000,maxFee:1000000,objects:['Yes','One pool','No'],actions:[['settle','Oracle: Yes wins',{yesWins:true}],['settle','Oracle: No wins',{yesWins:false}],['refund','Refund both sides',{refundBy:'yes'}]]},
 proof:{title:'A valid proof unlocks the payout.',description:'Try taking the payout without a proof. Then use a published example proof to unlock it. The remaining test coins return to your wallet.',amount:50000000,maxFee:20000000,objects:['Proof','Verify','Payout'],actions:[['verify','Verify proof and pay',{}]]}
};
let sdk,rpc,templates,keys=[],password='',session=null,contract=null,kind='escrow',plan=null,busy=false,exported=false,activeAccount=0,accountBalances=[0n,0n,0n],pendingMode=null,autoSession=false,operationLabel='',faucetClaim=null,observeTimer=null;
const STORE='kaspa-public-encrypted-recovery-v1',AUTO_STORE='kaspa-disposable-session-v1',AUTO_SECRET='kaspa-disposable-secret-v1',FAUCET_STORE='kaspa-disposable-faucet-v1';
const scenarioNames={escrow:'Escrow',treasury:'Shared treasury',prediction:'Prediction',proof:'Proof payout',token:'Token',receipt:'Backed receipt'},scenarioOrder=Object.keys(scenarioNames);
const kas=value=>`${(Number(value)/1e8).toLocaleString('en-US',{maximumFractionDigits:8})} tKAS`;
const message=(value,error=false)=>{set('message',value);q('message').dataset.error=String(error);};
const timeout=(promise,ms=12000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>{const error=new Error('Node timeout');error.safeMessage='The node did not respond. Check again before taking another action.';reject(error);},ms))]);
async function action(fn,label='Checking Testnet-10…'){
 if(busy){message(`${operationLabel} You can choose another example while this finishes.`);return;}
 busy=true;operationLabel=label;const trigger=document.activeElement?.closest('button'),triggerText=trigger?.textContent;if(trigger&&root.contains(trigger)&&!trigger.matches('[data-public-kind],[data-public-asset-kind]'))trigger.textContent=label;const disabledFields=[...root.querySelectorAll('input,select')].map(el=>[el,el.disabled]);for(const [el]of disabledFields)el.disabled=true;root.setAttribute('aria-busy','true');message(label);
 try{await fn();}catch(error){message(error?.safeMessage||'This action could not complete. Nothing is retried automatically. Check the connection or balance and try again.',true);}
 finally{busy=false;if(trigger?.isConnected&&trigger.textContent===label)trigger.textContent=triggerText;for(const [el,wasDisabled]of disabledFields)if(el.isConnected)el.disabled=wasDisabled;if(keys.length)q('account-select').disabled=hasPendingOriginal()||assetsUI.pending();root.removeAttribute('aria-busy');if(pendingMode){const next=pendingMode;pendingMode=null;activateMode(next);modeMessage(next);}if(q('message').textContent===label)message('Ready. Choose what you want to try next.');operationLabel='';if(keys.length&&(hasPendingOriginal()||assetsUI.pending()||assetsUI.hasUnaccepted?.()||(faucetClaim?.transactionId&&!faucetClaim.observed)))scheduleObservation();}
}

function fail(text){const error=new Error(text);error.safeMessage=text;throw error;}
// The SDK resolver probes cross-origin discovery URLs that emit WebKit page errors.
// Use the verified Testnet-10 RPC directly; a failed connection remains a visible failure.
async function initialize(){if(!sdk){sdk=await import('/assets/kaspa/kaspa.js');await sdk.default({module_or_path:'/assets/kaspa/kaspa_bg.wasm'});const response=await fetch('/assets/public-templates.json');if(!response.ok)fail('Contract templates are unavailable.');templates=await response.json();if(templates.version!==1||templates.network!==PUBLIC_NETWORK)fail('The installed templates are not for this Testnet-10 application.');}if(!rpc){for(const options of [{url:'wss://muon-10.kaspa.blue/kaspa/testnet-10/wrpc/borsh',networkId:PUBLIC_NETWORK}]){const candidate=new sdk.RpcClient(options);try{await timeout(candidate.connect({blockAsyncConnect:true,timeoutDuration:6000}),8000);rpc=candidate;break;}catch{try{await candidate.disconnect();}catch{}}}if(!rpc)fail('A Testnet-10 connection could not be established. Try restoring or connecting again.');}await nodeInfo();}
window.addEventListener('pagehide',()=>{if(rpc)rpc.disconnect().catch(()=>{});});
async function nodeInfo(){const [info,dag,estimate]=await Promise.all([timeout(rpc.getServerInfo()),timeout(rpc.getBlockDagInfo()),timeout(rpc.getFeeEstimate())]);if(info.networkId!==PUBLIC_NETWORK||info.isSynced!==true||info.hasUtxoIndex!==true)fail('Sending is blocked: a synchronized Testnet-10 node with a UTXO index is required.');const feeRate=Math.max(100,Math.ceil(estimate.estimate.priorityBucket.feerate));if(!Number.isFinite(feeRate)||feeRate>100000)fail('The node returned an unusable fee estimate.');set('connection','Connected to Testnet-10');return {...info,pastMedianTime:dag.pastMedianTime,feeRate};}

function newKey(){for(let i=0;i<8;i++){const bytes=crypto.getRandomValues(new Uint8Array(32));try{return new sdk.PrivateKey(Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''));}catch{}}fail('Could not create a disposable key.');}
const owner=()=>keys[activeAccount].toPublicKey().toXOnlyPublicKey().toString();
const walletAddress=()=>keys[0].toAddress(PUBLIC_NETWORK).toString();
const fundingAddress=()=>keys[activeAccount].toAddress(PUBLIC_NETWORK).toString();
async function refresh(checked=false){if(!checked)await nodeInfo();const addresses=keys.map(key=>key.toAddress(PUBLIC_NETWORK).toString()),{entries}=await timeout(rpc.getUtxosByAddresses(addresses));for(let index=0;index<3;index++){const amount=entries.filter(e=>e.address?.toString()===addresses[index]||e.entry.scriptPublicKey.script===sdk.payToAddressScript(new sdk.Address(addresses[index])).script).reduce((sum,e)=>sum+BigInt(e.amount),0n);accountBalances[index]=amount;q('account-select').options[index].textContent=`${['Main','Second','Third'][index]} account · ${kas(amount)}`;}const selected=entries.filter(e=>e.entry.scriptPublicKey.script===sdk.payToAddressScript(new sdk.Address(fundingAddress())).script);set('balance',kas(selected.reduce((sum,e)=>sum+BigInt(e.amount),0n)));q('address').value=fundingAddress();q('account-select').disabled=hasPendingOriginal()||assetsUI.pending();updateFaucet();return selected;}

function scenarioSlot(){return {contract:session?.contract||null,completed:session?.completed??true,...(session?.journal?{journal:session.journal}:{})};}
function stashScenario(){if(session?.contract){session.scenarios??={};session.scenarios[session.contract.kind]=scenarioSlot();}}
function hasPendingOriginal(){return Boolean(session?.journal&&!session.journal.observed)||Object.values(session?.scenarios||{}).some(slot=>slot.journal&&!slot.journal.observed);}
function loadScenario(next){stashScenario();const slot=session?.scenarios?.[next];kind=next;contract=slot?.contract?instantiatePublicContract(sdk,templates.templates[next],slot.contract.state):null;if(session){session.contract=slot?.contract||null;session.completed=slot?.completed??true;if(slot?.journal)session.journal=slot.journal;else delete session.journal;}}
function markChoices(next){for(const button of root.querySelectorAll('[data-public-kind],[data-public-asset-kind]')){const name=button.dataset.publicKind||button.dataset.publicAssetKind;button.setAttribute('aria-pressed',String(name===next));button.dataset.complete=String(Boolean(session?.scenarios?.[name]?.completed&&session.scenarios[name].journal?.acceptingBlock)||Boolean(session?.guided?.[name]));}}
function showWallet(){q('start').hidden=true;q('wallet').hidden=false;q('address').value=fundingAddress();activateMode(kind);}
function paintKind(next){markChoices(next);q('assets').hidden=true;q('example').hidden=false;q('review').hidden=true;q('next').hidden=true;const spec=kinds[next];set('title',spec.title);set('description',spec.description);set('cost',next==='proof'?'Lock 0.5 test coins. The proof fee can use up to 0.2 test coins. The deposit fee is at most 0.01.':'Lock 0.2 tKAS. Each ordinary transaction costs at most 0.01 tKAS.');set('prepare',`Lock ${Number(spec.amount)/1e8} test coins`);q('object').replaceChildren(...spec.objects.map((label,index)=>{const box=document.createElement('div');box.className='public-object-box';const small=document.createElement('span');small.textContent=label;const number=document.createElement('strong');number.textContent=index===1?kas(spec.amount):index===0?'①':'②';box.append(small,number);return box;}));}
function selectKind(next){navigateMode(next);}
function navigateMode(next){if(busy){pendingMode=next;markChoices(next);q('contract').hidden=true;q('receipt').hidden=true;q('next').hidden=true;if(kinds[next])paintKind(next);else{q('assets').hidden=true;q('example').hidden=false;set('title',scenarioNames[next]||'Send test coins');set('description',`Opening this example when the current check finishes. ${operationLabel}`);q('object').replaceChildren();q('prepare').hidden=true;set('cost','');}message(`${scenarioNames[next]||'Payment'} selected. ${operationLabel}`);return;}plan=null;q('review').hidden=true;assetsUI.invalidate();activateMode(next);modeMessage(next);}
function modeMessage(next){message(hasPendingOriginal()||assetsUI.pending()?`${scenarioNames[next]||'Payment'} selected. A previous transaction is still being checked; you can explore while it resolves.`:`${scenarioNames[next]||'Payment'} is ready. Choose the next action below.`);}
function activateMode(next){plan=null;q('review').hidden=true;assetsUI.invalidate();if(!kinds[next]){stashScenario();openAssetsNow(next);return;}loadScenario(next);paintKind(next);q('receipt').hidden=!session?.journal;q('contract').hidden=!contract;q('prepare').hidden=Boolean(contract&&!session?.completed);if(contract)showContract();if(session?.journal)showReceipt();showNext();}
function showNext(){const complete=Boolean(session?.completed&&session?.journal?.acceptingBlock);q('next').hidden=!complete;if(!complete)return;stashScenario();markChoices(kind);const next=scenarioOrder[scenarioOrder.indexOf(kind)+1];set('next-copy',`${scenarioNames[kind]} completed. The node accepted the transaction.`);set('next-button',next?`Next: ${scenarioNames[next]}`:'Try another example');q('next-button').dataset.next=next||'escrow';}

function baseState(info){const [a,b,c]=keys.map(key=>key.toPublicKey().toXOnlyPublicKey().toString()),now=Number(info.pastMedianTime),base={principal:kinds[kind].amount,maxFee:kinds[kind].maxFee};if(!Number.isSafeInteger(now))fail('The node did not provide a usable median time.');if(kind==='escrow')return {...base,buyer:a,seller:b,arbiter:c,refundAfter:now+120000};if(kind==='treasury')return {...base,memberA:a,memberB:b,memberC:c};if(kind==='prediction')return {...base,yesOwner:a,noOwner:b,oracle:c,resolveAfter:now+15000,refundAfter:now+60000};return {...base,owner:a};}
function showContract(){q('contract').hidden=false;updateChallenge();q('contract-address').value=contract.address;set('principal',kas(contract.state.principal));q('actions').hidden=!(session?.journal?.funding&&session.journal.observed);q('fund').disabled=!exported||Boolean(session?.journal);q('fund').hidden=Boolean(session?.journal);q('prepare').hidden=!session?.completed;q('backup-confirm').checked=true;const buttons=kinds[kind].actions.map(([entry,label,parameters],index)=>{const button=document.createElement('button');button.textContent=label;if(index===0)button.className='primary';button.addEventListener('click',()=>action(()=>reviewSpend(entry,parameters,label),`Sending: ${label}…`));return button;});q('action-options').replaceChildren(buttons[0]);if(buttons.length>1){const details=document.createElement('details');details.className='detail public-other-actions';const summary=document.createElement('summary');summary.textContent='Other allowed actions';details.append(summary,...buttons.slice(1));q('action-options').append(details);}}

async function challenge(){
 if(!contract)fail('Start this example first.');const info=await nodeInfo(),entries=await checkContract(true);if(entries.length!==1)fail('Deposit the test coins before trying this rule.');let text;
 if(kind==='escrow'){try{buildPublicSpend(sdk,{contract,utxo:entries[0],entry:'refund',pastMedianTime:info.pastMedianTime,feeRate:info.feeRate});text='The deadline has now passed, so a buyer refund is allowed. No transaction was sent; choose the timed refund below to review it.';}catch(error){if(!error.message.includes('median time'))throw error;text='Blocked before signing: the node’s median time has not reached the refund deadline. A buyer release or arbiter decision can pay out earlier.';}}
 else{const entry=kind==='treasury'?'spend':kind==='prediction'?'settle':'verify',parameters=kind==='treasury'?{pair:0}:kind==='prediction'?{yesWins:true}:{};let testPlan;try{testPlan=buildPublicSpend(sdk,{contract,utxo:entries[0],entry,parameters,pastMedianTime:info.pastMedianTime,feeRate:info.feeRate});}catch(error){if(kind==='prediction'&&error.message.includes('median time')){text='Blocked before signing: settlement is still time-locked. After that deadline, it also requires the oracle’s signature.';}else throw error;}
  if(testPlan){if(kind==='treasury'){if(testPlan.signers.length!==2)fail('This template did not require the expected two signatures.');text='Blocked before signing: the selected withdrawal requires two different member signatures. One signature leaves one required authorization missing.';}else if(kind==='prediction'){if(testPlan.signers[0]===contract.state.yesOwner)fail('The template did not require the expected oracle.');text='Blocked before signing: a participant’s key is not the oracle key required by this settlement. Choose an oracle action below.';}else{if(!testPlan.args[1])fail('The proof fixture is unavailable.');text='Blocked before signing: this payout requires proof bytes. Supplying no proof cannot satisfy the proof-verification action. The next action includes the published example proof.';}}
 }
 set('challenge-result',text);message('Rule checked locally before signing. No transaction was sent.');
}

function updateChallenge(){const copy={escrow:['Try taking a refund before the deadline.','Try an early refund'],treasury:['Try approving the withdrawal with only one member.','Try one signature'],prediction:['Try choosing the outcome as a participant instead of the oracle.','Try without the oracle'],proof:['Try taking the payout without supplying a proof.','Try without a proof']};set('challenge-copy',copy[kind][0]);set('challenge',copy[kind][1]);set('challenge-result','');}

const encode=bytes=>{let result='';for(let index=0;index<bytes.length;index+=32768)result+=String.fromCharCode(...bytes.subarray(index,index+32768));return btoa(result);},decode=text=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
async function encryptionKey(secret,salt){const raw=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encryptRecovery(){if(password.length<12)fail('Use a recovery password of at least 12 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await encryptionKey(password,salt);const payload={version:1,network:PUBLIC_NETWORK,keys:keys.map(key=>key.toString()),walletAddress:walletAddress(),session};const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return {version:1,network:PUBLIC_NETWORK,kdf:'PBKDF2-SHA256',iterations:250000,salt:encode(salt),iv:encode(iv),ciphertext:encode(new Uint8Array(ciphertext))};}
async function persist(){stashScenario();const encrypted=await encryptRecovery();try{const storage=autoSession?sessionStorage:localStorage,key=autoSession?AUTO_STORE:STORE;storage.setItem(key,JSON.stringify(encrypted));if(storage.getItem(key)!==JSON.stringify(encrypted))throw new Error();}catch{fail('Encrypted recovery could not be saved in this browser. New submissions are blocked. Enable browser storage or use another browser.');}return encrypted;}
function download(value){const blob=new Blob([JSON.stringify(value)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kaspa-testnet-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function strictFields(value,names){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(key=>names.includes(key));}
function transactionOutputs(tx){return tx.outputs.map((out,index)=>({index,amount:String(out.value),address:sdk.addressFromScriptPublicKey(out.scriptPublicKey,PUBLIC_NETWORK).toString(),script:out.scriptPublicKey.script}));}
function recoveredSession(value,restored){
 if(!strictFields(value,['contract','completed','journal','assets','scenarios','guided'])||typeof value.completed!=='boolean')fail('Invalid recovered session.');
 if(value.scenarios!==undefined){if(!strictFields(value.scenarios,Object.keys(kinds))||Object.keys(value.scenarios).length>4)fail('Invalid recovered scenario map.');for(const [name,slot] of Object.entries(value.scenarios)){if(!strictFields(slot,['contract','completed','journal'])||slot.contract?.kind!==name)fail('Invalid recovered scenario.');const checked=recoveredSession({...slot},restored);value.scenarios[name]={contract:checked.value.contract,completed:checked.value.completed,...(checked.value.journal?{journal:checked.value.journal}:{})};}}
 if(value.guided!==undefined&&(!strictFields(value.guided,scenarioOrder)||Object.values(value.guided).some(flag=>typeof flag!=='boolean')))fail('Invalid guided progress.');
 if(value.contract===null){if(value.journal)fail('A transaction journal requires its contract.');value.assets=validatePublicAssetsState(sdk,templates.templates,value.assets,restored.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()));return {rebuilt:null,value};}
 value.assets=validatePublicAssetsState(sdk,templates.templates,value.assets,restored.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()));
 const saved=value.contract;
 if(!strictFields(saved,['kind','state','script','address','templateVersion'])||!kinds[saved.kind]||saved.templateVersion!==1)fail('Invalid recovered contract.');
 const rebuilt=instantiatePublicContract(sdk,templates.templates[saved.kind],saved.state);
 if(rebuilt.script!==saved.script||rebuilt.address!==saved.address)fail('Recovered contract differs from the installed template.');
 const publicKeys=restored.map(k=>k.toPublicKey().toXOnlyPublicKey().toString());
 const roles=Object.entries(saved.state).filter(([name])=>!['principal','maxFee','refundAfter','resolveAfter'].includes(name));
 if(roles.some(([,key])=>!publicKeys.includes(key)))fail('A recovered role does not match this wallet’s keys.');
 if(value.journal){
  const j=value.journal;
  if(!strictFields(j,['id','transaction','funding','observed','submitted','outputs','attempted','checkpoint','scanCursor','acceptingBlock','scanCaughtUp','outputsObserved'])||typeof j.transaction!=='string'||j.transaction.length>750000||typeof j.funding!=='boolean'||typeof j.observed!=='boolean'||typeof j.submitted!=='boolean'||(j.attempted!==undefined&&typeof j.attempted!=='boolean'))fail('Invalid recovered transaction journal.');
  const recovered=derivePublicRecoveryPlan(sdk,{contract:rebuilt,journal:j,keysPublic:publicKeys});
  const outputs=transactionOutputs(recovered.transaction);
  j.outputs=outputs;j.observed=false;j.outputsObserved=false;if(j.checkpoint&&!/^[a-f0-9]{64}$/.test(j.checkpoint))fail('Invalid receipt checkpoint.');j.scanCursor=j.checkpoint||null;j.acceptingBlock=null;j.scanCaughtUp=false;
 }
 value.completed=false;return {rebuilt,value};
}
async function restore(fromLocal=false,automatic=false){
 let envelope;if(fromLocal){const saved=(automatic?sessionStorage:localStorage).getItem(automatic?AUTO_STORE:STORE);if(!saved||saved.length>4000000)fail('No valid encrypted recovery is saved in this browser.');envelope=JSON.parse(saved);}else{const file=q('import-file').files[0];if(!file||file.size>4000000)fail('Choose a recovery JSON file smaller than 4 MB.');envelope=JSON.parse(await file.text());}
 if(!strictFields(envelope,['version','network','kdf','iterations','salt','iv','ciphertext'])||envelope.version!==1||envelope.network!==PUBLIC_NETWORK||envelope.kdf!=='PBKDF2-SHA256'||envelope.iterations!==250000)fail('This is not a supported Testnet-10 recovery file.');
 const salt=decode(envelope.salt),iv=decode(envelope.iv);if(salt.length!==16||iv.length!==12)fail('Invalid recovery file.');
 const secret=automatic?sessionStorage.getItem(AUTO_SECRET):q('import-password').value,key=await encryptionKey(secret,salt),clear=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,decode(envelope.ciphertext));
 const value=JSON.parse(new TextDecoder().decode(clear));
 if(!strictFields(value,['version','network','keys','walletAddress','session'])||value.version!==1||value.network!==PUBLIC_NETWORK||!Array.isArray(value.keys)||value.keys.length!==3||value.keys.some(k=>typeof k!=='string'||!/^[a-f0-9]{64}$/i.test(k)))fail('The decrypted recovery data is invalid.');
 try{await initialize();}catch(error){rpc=null;throw error;}const restored=value.keys.map(k=>new sdk.PrivateKey(k));
 if(restored[0].toAddress(PUBLIC_NETWORK).toString()!==value.walletAddress)fail('The recovery address does not match its key.');
 const checked=recoveredSession(value.session,restored);
 keys=restored;password=secret;autoSession=automatic;session=checked.value;contract=checked.rebuilt;if(contract)kind=contract.kind;exported=true;q('import-password').value='';
 showWallet();if(contract)showContract();q('backup').hidden=true;await refresh();if(contract)await checkContract();if(session.journal)showReceipt();
 if(automatic)message('Your disposable session is restored. Checking its transactions does not send them again.');else message('Recovery decrypted and addresses checked. The node will determine which outputs remain spendable.');
}

async function prepare(){if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(hasPendingOriginal())fail('Check the previous transaction before preparing another contract.');if(contract&&!session?.completed)fail('Finish the current contract first.');const info=await nodeInfo();contract=instantiatePublicContract(sdk,templates.templates[kind],baseState(info));const preflight=preflightPublicContract(sdk,contract,{feeRate:info.feeRate});session={assets:session?.assets,scenarios:session?.scenarios||{},guided:session?.guided||{},contract:{kind,state:contract.state,script:contract.script,address:contract.address,templateVersion:1},completed:false};set('exit-cost',`Exit preflight: ${preflight.exits.map(exit=>`${exit.entry} ${kas(exit.fee)}`).join(' · ')}. These are calculated fees; review the transaction before sending.`);exported=exported&&password.length>=12;showContract();q('backup').hidden=exported;await persist();set('step','Choose an action → Send → See the result');message('Contract prepared and saved in this tab. Review its deposit next.');}
async function checkContract(checked=false){if(!checked)await nodeInfo();const {entries}=await timeout(rpc.getUtxosByAddresses([contract.address]));const exact=entries.filter(e=>BigInt(e.amount)===BigInt(contract.state.principal)&&e.entry.scriptPublicKey.version===0&&!e.entry.covenantId&&e.entry.scriptPublicKey.script===sdk.payToScriptHashScript(contract.script).script&&(!session?.journal?.funding||(e.outpoint.transactionId===session.journal.id&&e.outpoint.index===0)));q('actions').hidden=exact.length!==1;q('fund').hidden=exact.length>0||Boolean(session?.completed&&session?.journal);q('fund').disabled=!exported||exact.length>0||Boolean(session?.journal&&!session.journal.observed);set('contract-status',exact.length===1?'The node currently reports the exact contract output as unspent. Choose an action below.':exact.length>1?'More than one matching output exists. New actions are blocked to avoid choosing the wrong deposit.':'No exact unspent contract output is visible at this node.');return exact;}
function showReview(purpose){q('review').hidden=false;set('review-purpose',purpose);const total=plan.transaction.inputs.reduce((sum,input)=>sum+BigInt(input.utxo.amount),0n);const items=[['Network',PUBLIC_NETWORK],['Fee',kas(plan.fee)],['Total input',kas(total)],...plan.transaction.outputs.map((out,index)=>[`Output ${index+1} · ${kas(out.value)}`,sdk.addressFromScriptPublicKey(out.scriptPublicKey,PUBLIC_NETWORK)?.toString()||'Contract output'])];q('review-details').replaceChildren(...items.flatMap(([label,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;return [dt,dd];}));q('submit').disabled=false;q('submit').textContent='Send to Testnet-10';q('submit').hidden=!q('manual-review').checked;q('review').open=q('manual-review').checked;if(q('manual-review').checked)q('review').focus();}
async function reviewFunding(){if(assetsUI.pending()||hasPendingOriginal())fail('A previous transaction is still being checked. You can explore other examples while it resolves.');if(!exported)fail('This browser could not save the disposable session.');const info=await nodeInfo(),entries=await refresh(true);if((await checkContract(true)).length)fail('This contract is already funded.');if(entries.reduce((sum,e)=>sum+e.amount,0n)<=BigInt(contract.state.principal))fail('Get test coins first, then start this example.');plan=buildPublicFunding(sdk,{contract,fundingUtxos:entries.slice(0,8),owner:owner(),feeRate:info.feeRate});plan.reviewedAt=Date.now();showReview(`Lock ${kas(contract.state.principal)} in this ${kind} contract. Change returns to your test wallet.`);if(!q('manual-review').checked)await submit();}

async function reviewSpend(entry,parameters,label){if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(hasPendingOriginal())fail('Check the pending transaction first.');const info=await nodeInfo(),entries=await checkContract(true);if(entries.length!==1)fail('Exactly one matching unspent contract output is required.');try{plan=buildPublicSpend(sdk,{contract,utxo:entries[0],entry,parameters,pastMedianTime:info.pastMedianTime,feeRate:info.feeRate});}catch(error){if(error.message.includes('median time')){const deadline=entry==='refund'?contract.state.refundAfter:contract.state.resolveAfter;fail(`This action unlocks in about ${Math.max(1,Math.ceil((Number(deadline)-Number(info.pastMedianTime))/1000))} seconds of node time. Try another example, then return. No transaction was sent.`);}throw error;}plan.reviewedAt=Date.now();showReview(label);if(!q('manual-review').checked)await submit();}
function showReceipt(){q('receipt').hidden=false;const j=session.journal;q('resume').hidden=j.observed;set('receipt-state',j.acceptingBlock?`This node includes the transaction in accepted-chain history (block ${j.acceptingBlock.slice(0,12)}…).`:j.observed?'The node currently reports this transaction’s exact outputs as unspent.':j.submitted?'The node returned the expected transaction ID. Output observation is still pending.':'Submission is uncertain or has not yet been attempted. Check the node before taking another action.');const link=q('transaction-link');link.textContent=j.id;link.href=`https://tn10.kaspa.stream/transactions/${j.id}`;}
async function submit(){
 if(assetsUI.pending())fail('Check the unresolved asset transaction first.');if(!plan)fail('Review a transaction first.');const current=await nodeInfo();
 if(current.feeRate>plan.mass.feeRate)fail('The current fee estimate increased. Cancel and review again before signing, or wait before resubmitting the saved transaction.');
 if(!plan.signed){
  if(Date.now()-plan.reviewedAt>60000)fail('The review expired. Cancel and review the current outputs again.');const {sink}=await timeout(rpc.getSink());
  await signPublicPlan(plan,(tx,index,{publicKey})=>{const key=keys.find(k=>k.toPublicKey().toXOnlyPublicKey().toString()===publicKey);if(!key)fail('The required role key is not in this wallet.');return sdk.createInputSignature(tx,index,key);});
  session.journal={checkpoint:sink,id:plan.transaction.id,transaction:plan.transaction.serializeToSafeJSON(),funding:Boolean(plan.funding),observed:false,submitted:false,outputs:transactionOutputs(plan.transaction)};plan.signed=true;
 }
 if(!plan.recoverySaved&&!plan.recovery){await persist();plan.recoverySaved=true;}
 if(session.journal.attempted&&!plan.recovery)fail('This transaction was already attempted. Check its node observation; it will not be submitted again automatically.');validatePublicPlan(plan);session.journal.attempted=true;await persist();q('submit').disabled=true;
 try{const result=await timeout(rpc.submitTransaction({transaction:plan.transaction,allowOrphan:false}));if(result.transactionId!==session.journal.id)fail('The node returned a different transaction ID. Treat this submission as uncertain.');session.journal.submitted=true;await persist();message('Submitted to Testnet-10. Check what the node now observes.');}finally{q('submit').hidden=true;showReceipt();plan=null;}await checkReceipt();
}
async function checkReceipt(){await nodeInfo();const j=session?.journal;if(!j)fail('No recorded transaction.');const {entries}=await timeout(rpc.getUtxosByAddresses([...new Set(j.outputs.map(out=>out.address))]));j.outputsObserved=j.outputs.every(out=>entries.some(e=>e.outpoint.transactionId===j.id&&e.outpoint.index===out.index&&String(e.amount)===out.amount&&e.entry.scriptPublicKey.version===0&&e.entry.scriptPublicKey.script===out.script&&!e.entry.covenantId));if(j.checkpoint)Object.assign(j,await observePublicAcceptance(rpc,j,{call:timeout}));j.observed=Boolean(j.acceptingBlock)||j.outputsObserved;session.completed=j.observed&&!j.funding;await persist();showReceipt();await refresh(true);await checkContract(true);showNext();if(!j.acceptingBlock)scheduleObservation();message(j.acceptingBlock?'Transaction found in this node’s accepted-chain history. This is a current observation, not a finality guarantee.':j.observed?'Matching transaction outputs observed at this node. This is a current UTXO observation, not a finality guarantee.':'Matching outputs are not yet visible. The transaction remains pending or uncertain; new spends stay blocked.');}
q('create').addEventListener('click',()=>action(async()=>{await initialize();keys=[newKey(),newKey(),newKey()];password=encode(crypto.getRandomValues(new Uint8Array(32)));autoSession=true;sessionStorage.setItem(AUTO_SECRET,password);sessionStorage.removeItem(FAUCET_STORE);faucetClaim=null;session={contract:null,completed:true,scenarios:{},guided:{}};exported=true;await persist();showWallet();q('backup').hidden=true;await refresh();message('Wallet ready. Get 10 free test coins, then choose an example.');},'Creating your fresh wallet…'));
q('import').addEventListener('click',()=>action(()=>restore(false)));q('import-local').addEventListener('click',()=>action(()=>restore(true)));q('refresh').addEventListener('click',()=>action(refresh));for(const button of root.querySelectorAll('[data-public-kind]'))button.addEventListener('click',()=>selectKind(button.dataset.publicKind));q('prepare').addEventListener('click',()=>action(async()=>{await prepare();await reviewFunding();},'Preparing this example and its deposit…'));
q('export').addEventListener('click',()=>action(async()=>{const chosen=q('backup-password').value;if(chosen.length<12)fail('Choose at least 12 characters for this optional backup.');const previous=password;password=chosen;try{download(await encryptRecovery());}finally{password=previous;}q('backup-password').value='';q('backup-confirm').disabled=false;message('Optional encrypted backup downloaded. Your disposable session stays ready.');}));q('backup-confirm').addEventListener('change',()=>action(async()=>{exported=q('backup-confirm').checked;set('step',exported?'3 · Recovery saved → Review funding → Verify':'2 · Save recovery → Review funding → Verify');if(contract)await checkContract();if(exported)q('backup').hidden=true;}));q('fund').addEventListener('click',()=>action(reviewFunding));q('check').addEventListener('click',()=>action(checkContract));q('submit').addEventListener('click',()=>action(submit));q('cancel').addEventListener('click',()=>{plan=null;q('review').hidden=true;});q('check-receipt').addEventListener('click',()=>action(checkReceipt));
window.addEventListener('beforeunload',event=>{if(!autoSession&&keys.length&&session&&!session.completed){event.preventDefault();event.returnValue='';}});

q('resume').addEventListener('click',()=>action(async()=>{const j=session?.journal;if(!j||j.observed)fail('No unresolved transaction needs recovery.');await nodeInfo();plan=derivePublicRecoveryPlan(sdk,{contract,journal:j,keysPublic:keys.map(key=>key.toPublicKey().toXOnlyPublicKey().toString())});showReview('Resubmit the identical saved transaction. Its ID, inputs, outputs, and fee remain unchanged.');q('submit').textContent='Submit the identical saved transaction';if(!q('manual-review').checked)await submit();}));

q('account-select').addEventListener('change',()=>action(async()=>{if(hasPendingOriginal()||assetsUI.pending())fail('Check the unresolved transaction before changing accounts.');assetsUI.invalidate();activeAccount=Number(q('account-select').value);plan=null;q('review').hidden=true;await refresh();if(!q('assets').hidden)assetsUI.render();}));
q('copy-address').addEventListener('click',()=>action(async()=>{await navigator.clipboard.writeText(fundingAddress());message('Receive address copied. Use Testnet-10 coins only.');}));

q('show-backup').addEventListener('click',()=>{q('backup').hidden=false;q('backup-password').focus();});

const assetsUI=createPublicAssetsUI(q('assets'),{
 context:()=>({sdk,templates:templates?.templates,rpc,owners:keys.map(key=>key.toPublicKey().toXOnlyPublicKey().toString()),addresses:keys.map(key=>key.toAddress(PUBLIC_NETWORK).toString()),account:activeAccount,balances:accountBalances,call:timeout}),
 action,message,fail,nodeInfo,refresh,requiresDownload:()=>false,requiresManualReview:()=>q('manual-review').checked,guided:true,onObserved:async(name,entry)=>{if((name==='token'&&entry==='move')||(name==='receipt'&&entry==='redeem')){session.guided??={};session.guided[name]=true;await persist();const selected=root.querySelector('[data-public-kind][aria-pressed="true"],[data-public-asset-kind][aria-pressed="true"]');markChoices(selected?.dataset.publicKind||selected?.dataset.publicAssetKind);}},nextScenario:name=>navigateMode(scenarioOrder[scenarioOrder.indexOf(name)+1]||'escrow'),
 getState:()=>session?.assets,
 saveState:async value=>{if(!session)fail('Create or restore a wallet first.');session.assets=value;await persist();},
 encrypted:persist,download,hasRecovery:()=>exported&&password.length>=12,pending:hasPendingOriginal,
 sign:(tx,index,{owner:publicKey})=>{const key=keys.find(key=>key.toPublicKey().toXOnlyPublicKey().toString()===publicKey);if(!key)fail('Required signing account is missing.');return sdk.createInputSignature(tx,index,key);}
});
function openAssetsNow(next){q('receipt').hidden=true;set('step','Choose an action → Send → See the result');q('example').hidden=true;q('contract').hidden=true;q('review').hidden=true;q('next').hidden=true;plan=null;markChoices(next);assetsUI.open(next);}
function openAssets(next){navigateMode(next);}

for(const button of root.querySelectorAll('[data-public-asset-kind]'))button.addEventListener('click',()=>openAssets(button.dataset.publicAssetKind));
q('send').addEventListener('click',()=>openAssets('payment'));

q('challenge').addEventListener('click',()=>action(challenge,'Checking this rule before signing…'));
q('next-button').addEventListener('click',()=>navigateMode(q('next-button').dataset.next));

function updateFaucet(){
 const endpoint=root.dataset.publicFaucetEndpoint;
 if(!faucetClaim){try{faucetClaim=JSON.parse(sessionStorage.getItem(FAUCET_STORE)||'null');}catch{faucetClaim=null;}}
 const claim=faucetClaim?.address===walletAddress()?faucetClaim:null;
 q('faucet').disabled=Boolean(claim?.observed)||!endpoint;
 set('faucet',claim?.observed?'10 test coins received':claim?'Check test-coin request':'Get 10 test coins');
 if(claim?.observed){set('faucet-status','Your 10 test coins arrived. Choose any example below.');set('step','Wallet ready · Try the rules → Send → See the result');}
 else if(claim?.transactionId)set('faucet-status','The faucet submitted your request. Waiting for its exact output at the Testnet-10 node…');
 else if(!endpoint)set('faucet-status','The demo faucet is temporarily unavailable. Your wallet is ready; you can return when it is connected.');
}
async function requestCoins(){
 const endpoint=root.dataset.publicFaucetEndpoint;if(!endpoint)fail('The demo faucet is not connected yet.');
 if(!faucetClaim||faucetClaim.address!==walletAddress())faucetClaim={address:walletAddress(),requestId:crypto.randomUUID(),requestedAt:Date.now()};
 if(faucetClaim.observed){message('This wallet already received its 10 test coins. Choose an example.');return;}
 sessionStorage.setItem(FAUCET_STORE,JSON.stringify(faucetClaim));
 {const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address:faucetClaim.address,requestId:faucetClaim.requestId}),signal:AbortSignal.timeout(20000)});const body=await response.json();if(!response.ok)fail(typeof body.error==='string'?body.error.slice(0,240):'The faucet could not send coins right now. Your request can be checked again safely.');if(body.network!==PUBLIC_NETWORK||body.amount!=='1000000000'||!/^[a-f0-9]{64}$/.test(body.transactionId||'')||!['pending','submitted','accepted'].includes(body.status))fail('The faucet returned an unexpected response. Check this same request again before trying anything else.');if(faucetClaim.transactionId&&faucetClaim.transactionId!==body.transactionId)fail('The faucet changed this request’s transaction ID. No new request will be created.');faucetClaim.transactionId=body.transactionId;sessionStorage.setItem(FAUCET_STORE,JSON.stringify(faucetClaim));}
 await observeFaucet();scheduleObservation();
}
async function observeFaucet(){if(!faucetClaim?.transactionId||faucetClaim.observed)return;if(!faucetClaim.autoRetried&&Date.now()-(faucetClaim.requestedAt||Date.now())>=15000){faucetClaim.autoRetried=true;sessionStorage.setItem(FAUCET_STORE,JSON.stringify(faucetClaim));await requestCoins();return;}await nodeInfo();const {entries}=await timeout(rpc.getUtxosByAddresses([faucetClaim.address]));const script=sdk.payToAddressScript(new sdk.Address(faucetClaim.address)).script;faucetClaim.observed=entries.some(e=>e.outpoint.transactionId===faucetClaim.transactionId&&e.outpoint.index===0&&e.amount===1000000000n&&e.entry.scriptPublicKey.version===0&&e.entry.scriptPublicKey.script===script&&!e.entry.covenantId);sessionStorage.setItem(FAUCET_STORE,JSON.stringify(faucetClaim));await refresh(true);message(faucetClaim.observed?'Your 10 test coins arrived. Pick an example and try its rules.':'The request was submitted. Waiting for the exact 10-coin output at the node…');}
async function observeJournal(j){const {entries}=await timeout(rpc.getUtxosByAddresses([...new Set(j.outputs.map(out=>out.address))]));j.outputsObserved=j.outputs.every(out=>entries.some(e=>e.outpoint.transactionId===j.id&&e.outpoint.index===out.index&&String(e.amount)===out.amount&&e.entry.scriptPublicKey.version===0&&e.entry.scriptPublicKey.script===out.script&&!e.entry.covenantId));if(j.checkpoint)Object.assign(j,await observePublicAcceptance(rpc,j,{call:timeout}));j.observed=Boolean(j.acceptingBlock)||j.outputsObserved;}
async function observeSavedScenarios(){await nodeInfo();stashScenario();for(const slot of Object.values(session?.scenarios||{})){if(slot.journal&&!slot.journal.acceptingBlock){await observeJournal(slot.journal);slot.completed=slot.journal.observed&&!slot.journal.funding;if(session.contract?.kind===slot.contract.kind){session.journal=slot.journal;session.completed=slot.completed;}}}await persist();await refresh(true);if(!q('example').hidden&&contract){await checkContract(true);if(session.journal)showReceipt();showNext();}markChoices(q('assets').hidden?kind:root.querySelector('[data-public-asset-kind][aria-pressed="true"]')?.dataset.publicAssetKind);}
let observationAttempts=0,observing=false;
function scheduleObservation(){if(observeTimer||observing)return;observationAttempts=0;const poll=async()=>{observeTimer=null;if(!keys.length)return;if(busy){observeTimer=setTimeout(poll,1200);return;}const originals=Object.values(session?.scenarios||{}).some(slot=>slot.journal&&!slot.journal.acceptingBlock)||Boolean(session?.journal&&!session.journal.acceptingBlock),asset=assetsUI.hasUnaccepted?.(),faucet=faucetClaim?.transactionId&&!faucetClaim.observed;if(!originals&&!asset&&!faucet)return;observing=true;await action(async()=>{if(faucet)await observeFaucet();if(originals)await observeSavedScenarios();if(asset&&assetsUI.check)await assetsUI.check();},'Checking the transaction at Testnet-10…');observing=false;if(++observationAttempts<12)observeTimer=setTimeout(poll,3000);else message('The node is taking longer to confirm this request. Your signed transaction is saved; use Check to continue without sending it again.');};observeTimer=setTimeout(poll,2500);}
q('faucet').addEventListener('click',()=>action(requestCoins,'Requesting your 10 free test coins…'));
if(sessionStorage.getItem(AUTO_SECRET)&&sessionStorage.getItem(AUTO_STORE))action(async()=>{await restore(true,true);scheduleObservation();},'Restoring this disposable session…');

root.addEventListener('click',event=>{if(busy&&!event.target.closest('[data-public-kind],[data-public-asset-kind]')){event.preventDefault();event.stopImmediatePropagation();message(`${operationLabel} The current action is still running.`);}},true);
