import {escape} from './components.mjs';
import {site} from './site.mjs';
import {withContents} from './page-contents.mjs';

const applicationPages=new Set(['applications.html','covenants.html','covenants-v4.html','covenants-v5.html','covenants-v6.html','wrap.html']);
const learnPages=new Set(['what-is-kaspa.html','why-kaspa-matters.html','skeptical-case.html','kaspa-mining.html','kaspa-origin-story.html','moose.html']);
function isCurrent(file,href){return file===href.slice(1)+'.html'||href==='/what-is-kaspa'&&learnPages.has(file);}

export function renderSiteShell(page){
  const editorial=!applicationPages.has(page.file),title=page.title===site.title?page.title:`${page.title} · ${site.title}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(page.description)}"><link rel="canonical" href="${site.domain}${page.publicPath??('/'+(page.file==='index.html'?'':page.file.replace('.html','')))}">${page.unlisted?'<meta name="robots" content="noindex, nofollow">':''}<link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:image" content="${site.domain}/og-kaspa-explained.png"><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/network-diagram.css"><link rel="stylesheet" href="/assets/mechanism-diagrams.css"><link rel="stylesheet" href="/assets/flow-diagrams.css">${editorial?'<link rel="stylesheet" href="/assets/site-design.css">':''}${page.file==='index.html'?'<link rel="stylesheet" href="/assets/use-case-demo.css">':''}<script>try{const t=new URLSearchParams(location.search).get('theme')||localStorage.getItem('kaspa-theme');if(t==='dark')document.documentElement.dataset.theme='dark';}catch{}</script><script type="module" src="/assets/app.mjs"></script></head>
  <body${editorial?' class="editorial-page"':page.file==='covenants.html'?' class="covenant-world-page"':''} data-page="${escape(page.file.replace('.html',''))}"><a class="skip" href="#main">Skip to content</a>
  <header class="site-header"><div class="header-inner"><a class="brand" href="/"${page.file==='index.html'?' aria-current="page"':''}><img src="/favicon.svg" width="28" height="28" alt="">Kaspa Explained</a><nav class="main-nav" id="main-nav" aria-label="Main navigation">${site.navigation.map(([label,href])=>`<a href="${href}"${isCurrent(page.file,href)?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-tools"><a href="/search" aria-label="Search explanations">Search</a><button class="theme-button" data-theme-toggle aria-label="Dark appearance" aria-pressed="false">◐</button><button class="menu-button" data-menu aria-expanded="false" aria-controls="main-nav">Menu</button></div></div></header>
  <main class="main" id="main">${withContents(page)}</main>
  <footer class="site-footer"><div class="footer-intro"><a class="brand" href="/"><img src="/favicon.svg" width="24" height="24" alt="">Kaspa Explained</a><p>Independent explanations of the network, its uses and its tradeoffs.</p><a href="/sources">How the guide checks its claims →</a></div><div class="footer-group"><p>Explore</p><nav aria-label="More explanations"><a href="/what-is-kaspa">How Kaspa works</a><a href="/playground">Interactive models</a><a href="/kaspa-mining">Mining and supply</a><a href="/money">Programmable money</a></nav></div><div class="footer-group"><p>References</p><nav aria-label="References"><a href="/status">Network and tool status</a><a href="/kips">Protocol specifications</a><a href="/kaspa-origin-story">Research and history</a><a href="/moose">Books by Moose</a></nav></div></footer></body></html>`;
}
