export const testnetPage={file:'testnet.html',title:'Testnet Workshop',description:'Create a small test payment, inspect the transaction, and verify the receipt on Kaspa Testnet-10.',body:`
<div class="page-intro"><p class="eyebrow">Testnet Workshop</p><h1>A payment you<br>can take apart.</h1><p class="lead">Create a request. Review the exact transaction. Send test coins and check what the node accepted.</p></div>
<aside class="testnet-notice"><strong>Testnet-10 only. Never intended for mainnet use.</strong><p>Experimental and unaudited. This local app creates disposable test wallets. Do not use personal wallet keys or send real funds.</p></aside>
<section class="workshop" data-testnet>
<div class="workshop-toolbar"><strong>Test wallet</strong><button class="quiet-button" data-test-connect>Connect to Testnet-10</button></div>
<p class="workshop-message" data-test-message role="status">Not connected. Nothing has been sent.</p>
<div data-test-account hidden><div class="account-summary"><div><span>Available</span><strong data-test-balance>Unavailable</strong></div><div><span>Maximum payment</span><strong>1 tKAS</strong></div><div><span>Total experiment limit</span><strong>10 tKAS, including fees</strong></div></div><label class="address-field"><span>Your disposable funding address</span><input readonly data-test-address aria-label="Disposable Testnet-10 funding address"></label><div class="action-row"><button class="quiet-button" data-copy-address>Copy address</button><a href="https://faucet-testnet.kaspanet.io/" target="_blank" rel="noopener noreferrer">Get test coins ↗</a></div><p class="small">The faucet may ask you to verify that you are human. Use this address, then refresh the balance. Test keys stay in this local server’s private data folder, not your browser or GitHub.</p></div>
<div class="workshop-body" data-test-tools hidden><div><h2>Request a payment</h2><form data-request-form><label class="amount-field"><span>Amount in tKAS</span><input name="amount" type="text" inputmode="decimal" value="0.1" maxlength="20" required></label><button class="primary-button">Create request</button></form><p class="small">0.01–1 tKAS. Each request gets a separate receiving address and expires after one hour.</p><label class="select-control request-picker"><span>Your requests</span><select data-request-picker><option value="">Choose a request</option></select></label><div class="action-row"><button class="quiet-button" data-test-review disabled>Review payment</button><button class="quiet-button" data-test-receipt disabled>Check receipt</button></div></div><div class="review-surface" data-test-review-result><p>Choose a request to review its payment. No transaction is signed until you approve the review.</p></div></div>
<section class="receipt-surface" data-test-receipt-result hidden></section>
</section>
<section class="chapter"><div class="section-title"><h2>What this experiment establishes</h2></div><div class="reading-rows"><article><h3>The request</h3><p>A receiving address and an exact amount. These are application data, not a separate token or smart contract.</p></article><article><h3>The transaction</h3><p>The signed spend, its destination, change, and actual fee. This workshop only supports a single transaction, with a maximum fee of 0.01 tKAS.</p></article><article><h3>The receipt</h3><p>The node’s accepted-transaction history, checked against the transaction ID, plus matching unspent outputs at the request address. Submission alone is not acceptance.</p></article></div></section>
<details class="detail"><summary>Limits, storage, and failure behavior</summary><div class="detail-body"><p>This local server controls its disposable test keys. It is not a production wallet or merchant service. Keys and transaction records persist locally across a restart; nothing is written to GitHub.</p><p>The application refuses mainnet and other testnets, unsynchronized nodes, oversized payments, batching, expired reviews, and duplicate sends. A missing submission response stays uncertain and blocks further spending until reconciled. Refreshing the page never resubmits.</p><p>Acceptance is one community node’s current observation. A later change can invalidate an earlier observation. If the provider cannot supply the original checkpoint, this app cannot reconstruct that receipt and will say so. It does not promise finality or run a full node.</p></div></details>
<p class="source-line"><a href="/build-on-kaspa">Tools and contract experiments ↗</a> · <a href="https://docs.kaspa.org/integrate/accepted-transactions">Acceptance integration documentation ↗</a></p>
<script type="module" src="/assets/testnet-app.mjs"></script>`};
