/** Shared, finite game-resource economy. No resource here represents native KAS. */
export const RESOURCES=Object.freeze(['crops','wood','ore','tools','bread']);
const bag=(v={})=>Object.fromEntries(RESOURCES.map(k=>[k,v[k]||0]));
const spec=[
 ['mira','Mira’s Farm',{crops:24,wood:4,tools:2},{crops:4,wood:8,tools:3,bread:3},{wood:1},{crops:4}],
 ['rowan','Rowan’s Mill',{wood:24,bread:3},{wood:4,bread:5,tools:3},{bread:1},{wood:4}],
 ['ivo','Ivo’s Mine',{ore:20,bread:4},{ore:4,bread:6,tools:3},{bread:1},{ore:3}],
 ['bea','Bea’s Workshop',{tools:8,crops:8,wood:4,ore:5},{tools:3,wood:7,ore:8,crops:5},{wood:1,ore:1},{tools:2}],
 ['nell','Nell’s Bakery',{bread:12,crops:10},{bread:4,crops:12,wood:3},{crops:1,wood:1},{bread:4}],
];
function inventory(v={}){for(const[k,n]of Object.entries(v))if(!RESOURCES.includes(k)||!Number.isSafeInteger(n)||n<0||n>1000000)throw Error('Invalid inventory');return bag(v);}
function isPlayer(m,id){return m.actors[id]?.kind==='player';}
function quantities(v){if(!v||typeof v!=='object'||Array.isArray(v)||!Object.keys(v).length)throw Error('Empty resource bundle');for(const [k,n]of Object.entries(v))if(!RESOURCES.includes(k)||!Number.isSafeInteger(n)||n<=0)throw Error('Invalid game resource quantity');return {...v};}
function reservations(m){if(!m.reserved){m.reserved={};for(const t of Object.values(m.trades))if(t.status==='prepared')reserve(m,t,1);}return m.reserved;}
function reserve(m,t,direction){const reserved=m.reserved||(m.reserved={});for(const[id,bundle]of [[t.from,t.give],[t.to,t.want]]){reserved[id]??=bag();for(const[k,n]of Object.entries(bundle))reserved[id][k]+=n*direction;}}
const available=(m,id,k)=>m.actors[id].inventory[k]-(reservations(m)[id]?.[k]||0);

function funded(m,id,b){return Object.entries(b).every(([k,n])=>available(m,id,k)>=n);}
function utility(a,b){return Object.entries(b).reduce((s,[k,n])=>s+n*((a.needs[k]||0)>a.inventory[k]?3:1),0);}
function terms(m,t){if(!funded(m,t.from,t.give)||!funded(m,t.to,t.want))return 'unfunded';return utility(m.actors[t.to],t.give)>=utility(m.actors[t.to],t.want)?'accept':'counter';}
export function createMarket({now=0,playerInventory={}}={}){if(!Number.isFinite(now)||now<0)throw Error('Invalid server time');inventory(playerInventory);return {version:1,time:now,tick:0,nextId:1,actors:Object.fromEntries([...spec.map(([id,name,inventory,needs,input,output])=>[id,{id,name,kind:'business',inventory:bag(inventory),needs:bag(needs),recipe:{input,output}}]),['player',{id:'player',name:'You',kind:'player',inventory:bag(playerInventory),needs:bag({bread:4,tools:2})}]]),trades:{},events:[],production:{consumed:bag(),created:bag()},assistants:{},assistant:{enabled:false,maxTradesPerTick:1,maxGive:bag(),spent:bag()},retiredTrades:0,consumption:bag()};}
export function proposeTrade(m,{from,to,give,want,ttl=60,requiresReceipt=false}){if(from===to||!Object.hasOwn(m.actors,from)||!Object.hasOwn(m.actors,to))throw Error('Unknown trade parties');if(!Number.isFinite(ttl)||ttl<=0||ttl>3600)throw Error('Invalid expiry');give=quantities(give);want=quantities(want);const id=`trade-${m.nextId++}`;const t={id,from,to,give,want,expires:m.time+ttl,status:'offered',requiresReceipt:!!requiresReceipt};m.trades[id]=t;t.decision=terms(m,t);return structuredClone(t);}
export function counterTrade(m,id,{give,want}={}){const t=open(m,id);const actor=m.actors[t.to];const offered=give||t.want;const scale=Math.max(1,Math.ceil(utility(actor,offered)/utility(actor,t.give)));const requested=want||Object.fromEntries(Object.entries(t.give).map(([k,n])=>[k,n*scale]));if(!funded(m,t.to,offered)||!funded(m,t.from,requested)){t.status='rejected';return {id:t.id,status:'rejected',reason:'Inventory cannot support a fair counteroffer'};}const next=proposeTrade(m,{from:t.to,to:t.from,give:offered,want:requested,ttl:t.expires-m.time,requiresReceipt:t.requiresReceipt});t.status='countered';return next;}
function open(m,id){const t=m.trades[id];if(!t)throw Error('Unknown offer');if(t.status!=='offered')throw Error('Offer no longer open');if(t.expires<=m.time){t.status='expired';throw Error('Offer expired');}return t;}
export function prepareTrade(m,id,{playerApproved=false}={}){const t=open(m,id);if((isPlayer(m,t.from)||isPlayer(m,t.to))&&!playerApproved)throw Error('Player approval required');const decision=playerApproved&&isPlayer(m,t.to)?(funded(m,t.from,t.give)&&funded(m,t.to,t.want)?'accept':'unfunded'):terms(m,t);if(decision!=='accept')return {status:decision};reserve(m,t,1);t.status='prepared';return structuredClone(t);}
export function commitTrade(m,id,{verifiedReceipt=null}={}){const t=m.trades[id];if(!t)throw Error('Unknown trade');if(t.status==='settled')return structuredClone(t);if(t.status!=='prepared')throw Error('Trade not prepared');if(t.requiresReceipt&&(typeof verifiedReceipt!=='string'||!verifiedReceipt||verifiedReceipt.length>256))throw Error('Verified receipt required');if(t.requiresReceipt&&Object.values(m.trades).some(x=>x.id!==id&&x.receipt===verifiedReceipt))throw Error('Receipt already used');for(const k of RESOURCES){m.actors[t.from].inventory[k]+=(t.want[k]||0)-(t.give[k]||0);m.actors[t.to].inventory[k]+=(t.give[k]||0)-(t.want[k]||0);}reserve(m,t,-1);t.status='settled';t.receipt=verifiedReceipt;t.settledAt=m.time;m.events.push({type:'barter',id,time:m.time});return structuredClone(t);}
export function acceptTrade(m,id,options={}){if(m.trades[id]?.status==='settled')return structuredClone(m.trades[id]);const t=prepareTrade(m,id,options);return t.status==='prepared'&&!t.requiresReceipt?commitTrade(m,id):t;}
export function cancelTrade(m,id){const t=m.trades[id];if(!t||!['offered','prepared'].includes(t.status))throw Error('Cannot cancel trade');if(t.status==='prepared'&&t.requiresReceipt)throw Error('Receipt settlement must be resolved by host');if(t.status==='prepared')reserve(m,t,-1);t.status='cancelled';}
export function registerMarketPlayer(m,{id,name='Player',inventory:initial={}}){if(typeof id!=='string'||!id||id.length>128||['__proto__','constructor','prototype'].includes(id))throw Error('Invalid player ID');if(Object.hasOwn(m.actors,id)){if(!isPlayer(m,id))throw Error('Actor ID already used');return structuredClone(m.actors[id]);}m.actors[id]={id,name:String(name).slice(0,60),kind:'player',inventory:inventory(initial),needs:bag({bread:4,tools:2})};return structuredClone(m.actors[id]);}
export function configureAssistant(m,{enabled=false,maxTradesPerTick=1,maxGive={},playerId='player'}={}){if(!isPlayer(m,playerId))throw Error('Unknown player');if(!Number.isInteger(maxTradesPerTick)||maxTradesPerTick<0||maxTradesPerTick>10)throw Error('Invalid trade cap');inventory(maxGive);const config={enabled:!!enabled,maxTradesPerTick,maxGive:bag(maxGive),spent:bag()};m.assistants[playerId]=config;if(playerId==='player')m.assistant=config;}
function assistant(m,id){return m.assistants[id]||(id==='player'?m.assistant:{enabled:false,maxTradesPerTick:1,maxGive:bag(),spent:bag()});}
function negotiate(m,a,b){const give=RESOURCES.find(k=>available(m,a.id,k)>0&&b.inventory[k]<b.needs[k]);const want=RESOURCES.find(k=>k!==give&&available(m,b.id,k)>0&&a.inventory[k]<a.needs[k]);if(!give||!want)return null;return {from:a.id,to:b.id,give:{[give]:1},want:{[want]:1}};}
function clearThreeParty(m){const agents=Object.values(m.actors).filter(a=>a.kind==='business');const item=(a,b)=>RESOURCES.find(k=>available(m,a.id,k)>(a.recipe.output[k]?0:a.needs[k])&&b.inventory[k]<b.needs[k]);for(const a of agents)for(const b of agents)for(const c of agents){if(a===b||b===c||a===c)continue;const ab=item(a,b),bc=item(b,c),ca=item(c,a);if(!ab||!bc||!ca)continue;for(const [from,to,k]of [[a,b,ab],[b,c,bc],[c,a,ca]]){from.inventory[k]--;to.inventory[k]++;}m.events.push({type:'barter',mode:'three-party',actors:[a.id,b.id,c.id],resources:[ab,bc,ca],time:m.time});return true;}return false;}
function trim(m){m.events=m.events.slice(-200);const finished=Object.values(m.trades).filter(t=>!t.receipt&&!['offered','prepared'].includes(t.status));for(const t of finished.slice(0,Math.max(0,Object.keys(m.trades).length-300))){delete m.trades[t.id];m.retiredTrades++;}}
/** Trusted server seconds; process at most 100 rounds and discard older catch-up time. */
export function stepMarket(m,now){if(!Number.isFinite(now)||now<m.time)throw Error('Server time must be monotonic');const elapsed=Math.floor((now-m.time)/10),rounds=Math.min(100,elapsed);if(elapsed>100)m.time+=(elapsed-100)*10;for(let i=0;i<rounds;i++){m.time+=10;m.tick++;for(const t of Object.values(m.trades))if(t.status==='offered'&&t.expires<=m.time)t.status='expired';for(const a of Object.values(m.actors)){if(a.kind!=='business')continue;if(m.tick%3===0){for(const k of ['bread','tools'])if(available(m,a.id,k)>1){a.inventory[k]--;m.consumption[k]++;}}if(a.recipe&&funded(m,a.id,a.recipe.input)&&Object.entries(a.recipe.output).every(([k,n])=>a.inventory[k]+n<=60)){for(const[k,n]of Object.entries(a.recipe.input)){a.inventory[k]-=n;m.production.consumed[k]+=n;}for(const[k,n]of Object.entries(a.recipe.output)){a.inventory[k]+=n;m.production.created[k]+=n;}m.events.push({type:'production',actor:a.id,time:m.time});}}
const counts={};const agents=Object.values(m.actors).sort((a,b)=>(b.kind==='player')-(a.kind==='player'));for(let x=0;x<agents.length;x++)for(let y=x+1;y<agents.length;y++){const a=agents[x],b=agents[y];if(a.kind==='player'&&b.kind==='player')continue;const p=negotiate(m,a,b);if(!p)continue;const player=a.kind==='player'?a:b.kind==='player'?b:null;if(player){const existing=Object.values(m.trades).find(t=>t.status==='offered'&&t.from===p.from&&t.to===p.to&&JSON.stringify(t.give)===JSON.stringify(p.give)&&JSON.stringify(t.want)===JSON.stringify(p.want));const quote=existing||proposeTrade(m,{...p,requiresReceipt:!!m.playerTradesRequireReceipt});const config=assistant(m,player.id),outgoing=player.id===p.from?p.give:p.want;if(!config.enabled||(counts[player.id]||0)>=config.maxTradesPerTick||Object.entries(outgoing).some(([k,n])=>config.spent[k]+n>config.maxGive[k]))continue;const t=acceptTrade(m,quote.id,{playerApproved:true});if(['settled','prepared'].includes(t.status)){const automatic=m.trades[t.id];if(automatic)automatic.delegated=true;counts[player.id]=(counts[player.id]||0)+1;for(const[k,n]of Object.entries(outgoing))config.spent[k]+=n;}}else acceptTrade(m,proposeTrade(m,p).id);}clearThreeParty(m);trim(m);}
return getMarketView(m);}
export function getMarketView(m,{playerId='player'}={}){return structuredClone({time:m.time,tick:m.tick,playerId,actors:m.actors,trades:m.trades,events:m.events.slice(-40),assistant:assistant(m,playerId),resourceNotice:'Game resources only. No native KAS balance or chain acceptance is modeled.'});}
